/**
 * batch-a5.data.ts
 * BATCH A-5 | Anandalite · Anatase · Andalusite · Ancestralite · Andradite Garnet
 * Added: 2026-05-29
 *
 * ⚠️  INTERPRETIVE / TRADITIONAL LAYER — NOT SCIENTIFIC DATA
 * Physics and mineral data sourced from IMA / Mindat / Webmineral conventions.
 * Metaphysical data sourced from established cross-cultural traditions.
 * All records conform to CrystalRecord nested schema.
 */

import type { CrystalRecord } from './crystal.schema';

export const BATCH_A5: CrystalRecord[] = [

  // ─────────────────────────────────────────────────────────────────────────
  // ANANDALITE (Iris Quartz / Aurora Quartz)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Anandalite',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: null,

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Anandalite',
      ima_formula:     'SiO₂',
      mindat_formula:  'SiO2',
      ima_status:      null,
      ima_year:        null,
      strunzten:       '4.DA.05',
      dana8ed:         null,
      crystal_system:  'Trigonal',
      hardness_min:    7.0,
      hardness_max:    7.0,
      specific_gravity_min: 2.63,
      specific_gravity_max: 2.65,
      cleavage:        'None',
      fracture:        'Conchoidal',
      tenacity:        'Brittle',
      luster:          ['Vitreous'],
      diaphaneity:     ['Transparent', 'Translucent'],
      colour:          'Colorless to white with vivid internal spectral iridescence — full rainbow visible under light due to natural internal fracture planes',
      streak:          'White',
      fluorescence:    'Weak to none',
      ri_min:          1.543,
      ri_max:          1.553,
      birefringence:   0.009,
      optical_type:    'U',
      shortdesc:       'Trade name for naturally iridescent iris quartz from Northern India (Himachal Pradesh). Internal rainbow effect caused by natural thin-film interference within micro-fracture planes inside the quartz — entirely natural, not treated or coated. Also called Aurora Quartz or Rainbow Quartz. The iridescence is the same optical phenomenon that "aura" vapor-deposited treatments attempt to simulate artificially.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-29267.html',
    },

    optical: {
      mineral_name:     'Anandalite',
      refractive_index: { n_omega: 1.544, n_epsilon: 1.553 },
      birefringence:    0.009,
      optical_sign:     '+',
      dispersion:       'Weak (0.013) — internal rainbow from thin-film interference, not dispersion',
      pleochroism:      'None in host quartz; rainbow varies with viewing angle',
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 380, max: 700 },
      spectra:          [],
    },

    color: {
      primary_color:          'Full spectrum iridescent (natural internal rainbow)',
      color_variants:         ['White/clear with rainbow', 'Pale gold with rainbow', 'Smoky with rainbow'],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.88, c: 0.05, h: 90 },
      hex:                    null,
      munsell:                null,
      color_temperature_k:    null,
      psychological_effects:  [
        'Pure joy — the full spectrum alive inside a single stone',
        'Natural miracle: the same rainbow that aura coatings imitate, but born from the Earth itself',
        'Light as information — every wavelength present simultaneously',
        'Energises without overloading; luminous but not harsh',
      ],
      harmonics: {
        complementary_hue: null,
        triadic_hues:      null,
        analogous_range:   [0, 360],
      },
    },

    metaphysical: {
      mineral_name:     'Anandalite',
      chakra_primary:   'Crown',
      chakra_secondary: ['Third Eye', 'Heart', 'Higher Crown'],
      element:          ['Aether', 'Air', 'Water'],
      planet:           ['Sun', 'Neptune', 'Uranus'],
      archetype:        ['Oracle', 'Mystic', 'Healer'],
      zodiac:           ['Aquarius', 'Pisces', 'Libra'],
      numerology:       9,
      intention:        'Kundalini awakening — joy, full-spectrum activation, divine light embodied',
      traditions:       [
        'Northern Indian mineral tradition (Himachal Pradesh)',
        'Modern Crystal Healing',
        'Sanskrit: Ananda = bliss/joy',
      ],
      properties: [
        'Name derives from Sanskrit "Ananda" — bliss, divine joy',
        'Naturally iridescent iris quartz — rainbow is internal, entirely untreated',
        'Among the highest-vibration quartzes available — activates all chakras simultaneously',
        'Known as a kundalini activator — gently moves energy up the spine',
        'Eases depression and brings genuine joy; lifts emotional heaviness',
        'Supports development of psychic gifts and inner vision',
        'Excellent for reconciliation — helps move forward without losing the lesson',
        'The natural version of what aura crystals try to be — authentic vs. artificial',
      ],
      gaia_resonance:   'ClarusLens + SomnusVeil — full-spectrum joy activation, kundalini node, authentic light',
      safety_warning:   null,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ANATASE
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Anatase',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: null,

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Anatase',
      ima_formula:     'TiO₂',
      mindat_formula:  'TiO2',
      ima_status:      'A',
      ima_year:        null,
      strunzten:       '4.DB.05',
      dana8ed:         null,
      crystal_system:  'Tetragonal',
      hardness_min:    5.5,
      hardness_max:    6.0,
      specific_gravity_min: 3.79,
      specific_gravity_max: 3.97,
      cleavage:        'Perfect {001} and {011}',
      fracture:        'Subconchoidal',
      tenacity:        'Brittle',
      luster:          ['Adamantine', 'Metallic'],
      diaphaneity:     ['Transparent', 'Translucent', 'Opaque'],
      colour:          'Colorless, white, pale yellow, brown, indigo-blue, black; color from iron/niobium impurities',
      streak:          'Pale yellowish white',
      fluorescence:    'None',
      ri_min:          2.488,
      ri_max:          2.561,
      birefringence:   0.073,
      optical_type:    'U',
      shortdesc:       'Metastable polymorph of titanium dioxide (TiO₂). Tetragonal system. Named 1801 by Haüy from Greek anatasis (extension) for its elongated dipyramidal crystals. Converts irreversibly to rutile above ~600°C. Extremely high refractive index (2.49–2.56) — higher than diamond (2.42). Photocatalytic properties. Found in metamorphic and igneous rocks, alpine veins.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-213.html',
    },

    optical: {
      mineral_name:     'Anatase',
      refractive_index: { n_omega: 2.561, n_epsilon: 2.488 },
      birefringence:    0.073,
      optical_sign:     '-',
      dispersion:       'Very high — exceeds diamond',
      pleochroism:      'Dichroic: slate blue (e) / pale yellow-grey (o)',
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: null,
      spectra:          [],
    },

    color: {
      primary_color:          'Indigo-blue to black (most common gem quality); also pale yellow, colorless',
      color_variants:         ['Colorless/white (pure)', 'Pale yellow', 'Brown', 'Indigo-blue', 'Black'],
      dominant_wavelength_nm: 440,
      oklch:                  { l: 0.35, c: 0.14, h: 270 },
      hex:                    '#2d3a6b',
      munsell:                null,
      color_temperature_k:    null,
      psychological_effects:  [
        'Deep indigo — the inner cosmos, the threshold between mind and void',
        'Metallic adamantine luster combined with indigo: simultaneously earthly and stellar',
        'Very high RI creates extraordinary brilliance in small crystals — light concentrated',
        'The blue of deep night sky: introspective, expansive, timeless',
      ],
      harmonics: {
        complementary_hue: 90,
        triadic_hues:      [30, 150],
        analogous_range:   [250, 290],
      },
    },

    metaphysical: {
      mineral_name:     'Anatase',
      chakra_primary:   'Third Eye',
      chakra_secondary: ['Crown', 'Throat'],
      element:          ['Aether', 'Air'],
      planet:           ['Uranus', 'Neptune', 'Saturn'],
      archetype:        ['Sage', 'Alchemist', 'Oracle'],
      zodiac:           ['Aquarius', 'Capricorn'],
      numerology:       7,
      intention:        'Transformation under pressure — converting lower states into higher ones, photocatalysis as metaphor',
      traditions:       ['Modern Crystal Healing', 'Western Esotericism'],
      properties: [
        'Metastable TiO₂ — exists in a high-energy state, transforms irreversibly to rutile under heat',
        'The alchemical crystal: holds transformation potential without collapsing until the moment is right',
        'Photocatalytic in physics — literally activates and transforms things in the presence of light',
        'Extremely high refractive index — higher than diamond — concentrates and bends light intensely',
        'Rare as a collectible mineral; energetically precise and focused',
        'Supports radical transformation of perspective — seeing the world through entirely new angles',
        'Aligns with the Third Eye for deep inner vision and non-linear knowing',
        'Useful in GAIA for quantum state transitions — holding the between-state consciously',
      ],
      gaia_resonance:   'QuantumNexus + ClarusLens — metastable transformation, photocatalytic activation, light alchemy',
      safety_warning:   null,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ANDALUSITE (incl. Chiastolite variety)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Andalusite',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: null,

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Andalusite',
      ima_formula:     'Al₂SiO₅',
      mindat_formula:  'Al2SiO5',
      ima_status:      'A',
      ima_year:        null,
      strunzten:       '9.AF.10',
      dana8ed:         null,
      crystal_system:  'Orthorhombic',
      hardness_min:    6.5,
      hardness_max:    7.5,
      specific_gravity_min: 3.13,
      specific_gravity_max: 3.21,
      cleavage:        'Distinct {110}, indistinct {100}, poor {010}',
      fracture:        'Uneven to subconchoidal',
      tenacity:        'Brittle',
      luster:          ['Vitreous', 'Sub-Vitreous', 'Greasy'],
      diaphaneity:     ['Transparent', 'Translucent', 'Opaque'],
      colour:          'Brown, reddish-brown, olive-green, grey, white; Chiastolite variety shows black cross pattern from carbonaceous inclusions',
      streak:          'White',
      fluorescence:    'Weak yellowish to greenish under LW UV',
      ri_min:          1.629,
      ri_max:          1.650,
      birefringence:   0.009,
      optical_type:    'B',
      shortdesc:       'Aluminosilicate polymorph (with kyanite and sillimanite). Named for Andalusia, Spain. Strongly trichroic — shows different colors on three axes. Chiastolite variety contains carbonaceous inclusions forming a natural cross pattern. Used as a refractory material. Found in metamorphic rocks (pelitic schists, hornfels).',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-217.html',
    },

    optical: {
      mineral_name:     'Andalusite',
      refractive_index: { n_alpha: 1.629, n_beta: 1.633, n_gamma: 1.650 },
      birefringence:    0.009,
      optical_sign:     '-',
      dispersion:       'Weak to moderate',
      pleochroism:      'STRONG trichroic: olive-green / dark reddish-brown / yellowish-green (three distinct axes)',
      fluorescence_lw:  'Weak yellowish to greenish',
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 520, max: 680 },
      spectra:          [],
    },

    color: {
      primary_color:          'Reddish-brown to olive-green (strongly trichroic)',
      color_variants:         [
        'Reddish-brown (most common)',
        'Olive-green',
        'Yellowish-green',
        'Chiastolite: grey-brown with black cross',
        'Gem quality: multi-color play from trichroism',
      ],
      dominant_wavelength_nm: 600,
      oklch:                  { l: 0.52, c: 0.12, h: 60 },
      hex:                    '#8b6914',
      munsell:                null,
      color_temperature_k:    null,
      psychological_effects:  [
        'Earth tones — deeply grounding, stable, ancient',
        'Trichroism creates a colour-shifting quality: truth seen from different angles',
        'Chiastolite cross: the intersection of spirit and matter, four directions held in one',
        'Olive-green axis: growth, integration, heart-root connection',
      ],
      harmonics: {
        complementary_hue: 240,
        triadic_hues:      [180, 300],
        analogous_range:   [40, 80],
      },
    },

    metaphysical: {
      mineral_name:     'Andalusite',
      chakra_primary:   'Root',
      chakra_secondary: ['Heart', 'Solar Plexus'],
      element:          ['Earth', 'Fire'],
      planet:           ['Mars', 'Earth'],
      archetype:        ['Guardian', 'Warrior', 'Sage'],
      zodiac:           ['Virgo', 'Scorpio', 'Capricorn'],
      numerology:       5,
      intention:        'Grounded truth — seeing reality from all angles, standing at the crossroads with clarity',
      traditions:       [
        'Spanish (Andalusia — place of origin)',
        'Christian (Chiastolite cross — carried by pilgrims on the Way of St. James)',
        'Celtic (protective cross stone)',
        'Western Esotericism',
        'Modern Crystal Healing',
      ],
      properties: [
        'One of three aluminosilicate polymorphs — same formula as kyanite and sillimanite, different structure',
        'Chiastolite variety: natural black cross inside every stone — one of nature\'s most literal sacred symbols',
        'Carried by medieval pilgrims on the Camino de Santiago as a protective talisman',
        'Strongly trichroic — embodies the principle of seeing truth from multiple perspectives simultaneously',
        'Grounding and stabilising without heaviness — connects root to heart',
        'Supports intellectual honesty and facing difficult truths without flinching',
        'Excellent for those navigating crossroads — major life decisions, transitions',
        'Protective against psychic drain and negative thoughtforms',
      ],
      gaia_resonance:   'AnchorPrism + SovereignCore — crossroads clarity, grounded truth, multi-perspective seeing',
      safety_warning:   null,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ANCESTRALITE
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Ancestralite',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: null,

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Ancestralite',
      ima_formula:     'Fe₂O₃ · FeO(OH) · Fe₂O₃ · SiO₂ (composite)',
      mindat_formula:  'Composite: hematite + lepidocrocite + goethite + quartz',
      ima_status:      null,
      ima_year:        null,
      strunzten:       null,
      dana8ed:         null,
      crystal_system:  'Amorphous',
      hardness_min:    5.0,
      hardness_max:    6.5,
      specific_gravity_min: 3.5,
      specific_gravity_max: 4.5,
      cleavage:        'None (matrix composite)',
      fracture:        'Uneven',
      tenacity:        'Brittle',
      luster:          ['Metallic', 'Sub-Metallic', 'Earthy'],
      diaphaneity:     ['Opaque'],
      colour:          'Deep charcoal grey to black with red-brown iron oxide banding; iridescent silver-black metallic surface on hematite layers',
      streak:          'Red-brown (iron oxide dominant)',
      fluorescence:    'None',
      ri_min:          null,
      ri_max:          null,
      birefringence:   null,
      optical_type:    null,
      shortdesc:       'Trade name for a composite iron oxide mineral matrix from Brazil, composed primarily of hematite, lepidocrocite, and goethite with quartz inclusions. Not an IMA-recognized mineral species. Dense, heavy, metallic. Visually striking: layered black and red-brown banding. Sometimes also contains magnetite.',
      updttime:        null,
      mindat_url:      null,
    },

    optical: {
      mineral_name:     'Ancestralite',
      refractive_index: { n: 3.0 },
      birefringence:    null,
      optical_sign:     null,
      dispersion:       null,
      pleochroism:      null,
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: null,
      spectra:          [],
    },

    color: {
      primary_color:          'Charcoal-black with red-brown iron banding',
      color_variants:         ['Deep black (hematite dominant)', 'Red-black banded', 'Silver-black metallic', 'Brown-black (goethite-heavy)'],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.18, c: 0.06, h: 30 },
      hex:                    '#2a1a14',
      munsell:                null,
      color_temperature_k:    null,
      psychological_effects:  [
        'The darkest of reds and blacks — primal, ancestral, blood memory',
        'Iron red beneath black surface: life-force held under stillness',
        'Heavy and dense visually — communicates weight, permanence, rootedness',
        'Not ominous: protective density — the darkness of deep soil, not absence of light',
      ],
      harmonics: {
        complementary_hue: 200,
        triadic_hues:      [150, 270],
        analogous_range:   [10, 50],
      },
    },

    metaphysical: {
      mineral_name:     'Ancestralite',
      chakra_primary:   'Root',
      chakra_secondary: ['Earth Star', 'Sacral'],
      element:          ['Earth', 'Fire'],
      planet:           ['Earth', 'Mars', 'Pluto'],
      archetype:        ['Guardian', 'Ancestor', 'Sage'],
      zodiac:           ['Scorpio', 'Capricorn', 'Aries'],
      numerology:       8,
      intention:        'Ancestral healing — clearing inherited trauma, activating lineage gifts, soul-deep grounding',
      traditions:       [
        'Brazilian mineral tradition',
        'Modern Crystal Healing',
        'Ancestral healing practices (cross-cultural)',
      ],
      properties: [
        'Composite iron oxide matrix — carries the deep memory of iron-bearing Earth formations',
        'Said to be more magically potent than hematite alone — triple iron oxide combination',
        'Primary stone for ancestral healing work — clearing generational trauma and karmic patterns',
        'Activates Earth Star chakra — roots the bearer into the planetary energy field below the feet',
        'Draws the aura in close and tight — highly protective, seals the field',
        'Accesses Akashic records of the bloodline and soul lineage',
        'Supports cord-cutting from toxic ancestral patterns while honouring lineage gifts',
        'Dense and grounding — excellent for those who are ungrounded, scattered, or disembodied',
        'Works slowly and deeply — not a quick-activation stone; requires patient relationship',
      ],
      gaia_resonance:   'AnchorPrism + Noosphere — ancestral memory access, Earth Star grounding, lineage healing',
      safety_warning:   'Iron oxide composite — avoid ingestion. Do not use in water elixirs without indirect method. Wash hands after extended handling.',
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ANDRADITE GARNET (incl. Demantoid, Topazolite, Melanite varieties)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Andradite Garnet',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: null,

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Andradite Garnet',
      ima_formula:     'Ca₃Fe₂(SiO₄)₃',
      mindat_formula:  'Ca3Fe2(SiO4)3',
      ima_status:      'A',
      ima_year:        null,
      strunzten:       '9.AD.25',
      dana8ed:         null,
      crystal_system:  'Cubic',
      hardness_min:    6.5,
      hardness_max:    7.0,
      specific_gravity_min: 3.77,
      specific_gravity_max: 3.95,
      cleavage:        'None',
      fracture:        'Conchoidal to uneven',
      tenacity:        'Brittle',
      luster:          ['Adamantine', 'Resinous'],
      diaphaneity:     ['Transparent', 'Translucent', 'Opaque'],
      colour:          'Yellow (topazolite), green (demantoid), black (melanite), brown, red-brown',
      streak:          'White',
      fluorescence:    'None to weak',
      ri_min:          1.880,
      ri_max:          1.900,
      birefringence:   null,
      optical_type:    'Isotropic',
      shortdesc:       'Calcium iron garnet. Highest dispersion of all garnets — demantoid variety exceeds diamond in fire (0.057 vs diamond 0.044). Named for Brazilian mineralogist J.B. de Andrada e Silva. Varieties: Demantoid (green, rarest and most valuable garnet), Topazolite (yellow), Melanite (black, titaniferous). Demantoid famously shows "horsetail" inclusions of chrysotile fibers — a provenance marker.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-237.html',
    },

    optical: {
      mineral_name:     'Andradite Garnet',
      refractive_index: { n: 1.880 },
      birefringence:    null,
      optical_sign:     null,
      dispersion:       '0.057 — HIGHER than diamond (0.044). Highest dispersion of any garnet species.',
      pleochroism:      'None (isotropic — cubic system)',
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 490, max: 570 },
      spectra:          [],
    },

    color: {
      primary_color:          'Green (demantoid) / Yellow (topazolite) / Black (melanite)',
      color_variants:         [
        'Demantoid: vivid emerald to yellow-green',
        'Topazolite: pale to deep yellow',
        'Melanite: opaque black',
        'Brown-red (common variety)',
      ],
      dominant_wavelength_nm: 530,
      oklch:                  { l: 0.50, c: 0.22, h: 145 },
      hex:                    '#2d7a3a',
      munsell:                '5G 5/10',
      color_temperature_k:    null,
      psychological_effects:  [
        'Demantoid green: the most alive green — forest floor, vital, overflowing',
        'Dispersion higher than diamond: fire and life-force expressed as pure light',
        'Yellow-green spectrum: solar energy meeting heart chakra — generosity, abundance',
        'Melanite black: absolute protection, void-stillness, Saturn boundary',
      ],
      harmonics: {
        complementary_hue: 325,
        triadic_hues:      [265, 25],
        analogous_range:   [120, 165],
      },
    },

    metaphysical: {
      mineral_name:     'Andradite Garnet',
      chakra_primary:   'Heart',
      chakra_secondary: ['Root', 'Solar Plexus', 'Crown'],
      element:          ['Earth', 'Fire'],
      planet:           ['Venus', 'Mars', 'Saturn'],
      archetype:        ['Sovereign', 'Creator', 'Guardian'],
      zodiac:           ['Capricorn', 'Aquarius', 'Scorpio'],
      numerology:       6,
      intention:        'Dynamic strength — creativity, love expressed as vitality, abundance through grounded action',
      traditions:       [
        'Victorian jewellery tradition (demantoid highly prized — Fabergé used demantoid extensively)',
        'Roman (garnet general — protective for warriors)',
        'Western Esotericism',
        'Modern Crystal Healing',
      ],
      properties: [
        'Rarest garnet species in gem quality — demantoid is among the rarest gems on Earth',
        'Dispersion exceeds diamond — more fire, more life-force, more creative spark',
        'Stimulates creativity and artistic expression at the deepest level',
        'Strengthens relationships — fosters trust, commitment, and genuine mutual support',
        'Energises the body and clears stagnant energy from the field',
        'Melanite variety: extremely protective — seals the aura like armour',
        'Topazolite: gentle solar abundance, optimism, golden light of manifestation',
        'Named for the man who first classified Brazilian minerals — carries the spirit of the naturalist',
        'Demantoid horsetail inclusions (chrysotile) are its fingerprint — beauty with signature',
      ],
      gaia_resonance:   'ViriditasHeart + SovereignCore — creative vitality, heart-root connection, dynamic abundance',
      safety_warning:   'Demantoid inclusions may contain chrysotile (serpentine asbestos fibers). Do not grind, sand, or damage raw specimens. Polished stones safe for handling. Do not use raw demantoid in water elixirs.',
    },
  },

];

export default BATCH_A5;
