/**
 * src/crystals/db/batch-a4.data.ts
 * GAIA-OS Crystal Database — Batch A-4
 *
 * Entries:
 *   1. Albite
 *   2. Alexandrite
 *   3. Amazonite
 *   4. Amber
 *   5. Amethyst
 */

import type { CrystalRecord } from './crystal.schema';

export const BATCH_A4: CrystalRecord[] = [

  // ── 1. Albite ──────────────────────────────────────────────────────────────
  {
    name:        'Albite',
    trade_name:  false,
    mindat_id:   138,

    physical: {
      id:            138,
      longid:        'albite',
      guid:          '6f2e4a0b-3c1d-4e8f-a9b2-7c5d6e3f1a0b',
      name:          'Albite',
      ima_formula:   'NaAlSi₃O₈',
      mindat_formula: 'NaAlSi3O8',
      ima_status:    'A',
      ima_year:      1815,
      strunzten:     '9.FA.35',
      dana8ed:       '76.1.3.1',
      crystal_system: 'Triclinic',
      hardness_min:  6.0,
      hardness_max:  6.5,
      specific_gravity_min: 2.60,
      specific_gravity_max: 2.65,
      cleavage:      'Perfect on {001}, good on {010}',
      fracture:      'Conchoidal to uneven',
      tenacity:      'Brittle',
      luster:        ['Vitreous', 'Pearly on cleavage'],
      diaphaneity:   ['Transparent', 'Translucent'],
      colour:        'White, grey, bluish-white, greenish-white',
      streak:        'White',
      fluorescence:  null,
      ri_min:        1.528,
      ri_max:        1.540,
      birefringence: 0.011,
      optical_type:  'B',
      shortdesc:     'Sodium-rich end-member of the plagioclase feldspar series. Common rock-forming mineral.',
      updttime:      '2024-11-10T00:00:00Z',
      mindat_url:    'https://www.mindat.org/min-80.html',
      piezoelectric:    false,
      safe_for_water:   true,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Albite',
      refractive_index: { n_alpha: 1.528, n_beta: 1.532, n_gamma: 1.540 },
      birefringence:    0.011,
      optical_sign:     '+',
      dispersion:       'Weak',
      pleochroism:      null,
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: null,
      spectra:          [],
    },

    color: {
      primary_color:          'White',
      color_variants:         ['Grey', 'Bluish-white', 'Greenish-white'],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.96, c: 0.01, h: 220 },
      hex:                    '#f3f4f5',
      munsell:                'N 9/',
      color_temperature_k:    6500,
      psychological_effects:  ['Clarity', 'Neutrality', 'Mental calm'],
      harmonics: {
        complementary_hue: null,
        triadic_hues:      null,
        analogous_range:   null,
      },
    },

    color_layer: 'natural',
    yin_yang_pair: 'yang',

    metaphysical: {
      mineral_name:     'Albite',
      chakra_primary:   'Third Eye',
      chakra_secondary: ['Crown', 'Throat'],
      element:          ['Air', 'Aether'],
      planet:           ['Moon', 'Mercury'],
      archetype:        ['The Seeker', 'The Dreamer'],
      zodiac:           ['Gemini', 'Aquarius'],
      numerology:       1,
      angel_number:     111,
      intention:        'I perceive clearly. The veil lifts and truth shines through.',
      traditions:       ['Crystal healing', 'Lithotherapy'],
      properties:       [
        'Enhances intuition and psychic perception',
        'Supports lucid dreaming and astral travel',
        'Clears mental fog and enhances clarity',
        'Bridges conscious and unconscious mind',
      ],
      gaia_resonance:   'ClarusLens + SomnusVeil',
      safety_warning:   null,
    },
  },

  // ── 2. Alexandrite ────────────────────────────────────────────────────────
  {
    name:        'Alexandrite',
    trade_name:  false,
    mindat_id:   160,

    physical: {
      id:            160,
      longid:        'alexandrite',
      guid:          '7a3f5b1c-4d2e-4f9a-b0c3-8d6e7f4g2b1c',
      name:          'Alexandrite',
      ima_formula:   'BeAl₂O₄',
      mindat_formula: 'BeAl2O4',
      ima_status:    'A',
      ima_year:      1842,
      strunzten:     '4.BA.05',
      dana8ed:       '7.2.8.4',
      crystal_system: 'Orthorhombic',
      hardness_min:  8.5,
      hardness_max:  8.5,
      specific_gravity_min: 3.70,
      specific_gravity_max: 3.73,
      cleavage:      'Distinct on {110}',
      fracture:      'Conchoidal to uneven',
      tenacity:      'Brittle',
      luster:        ['Vitreous'],
      diaphaneity:   ['Transparent', 'Translucent'],
      colour:        'Green in daylight, red to purplish-red in incandescent light',
      streak:        'White',
      fluorescence:  'Weak red under UV',
      ri_min:        1.746,
      ri_max:        1.755,
      birefringence: 0.009,
      optical_type:  'B',
      shortdesc:     'Chromium-bearing variety of chrysoberyl famous for dramatic colour-change from green to red.',
      updttime:      '2024-10-15T00:00:00Z',
      mindat_url:    'https://www.mindat.org/min-100.html',
      piezoelectric:    false,
      safe_for_water:   true,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Alexandrite',
      refractive_index: { n_alpha: 1.746, n_beta: 1.748, n_gamma: 1.755 },
      birefringence:    0.009,
      optical_sign:     '+',
      dispersion:       'Moderate',
      pleochroism:      'Strong: green / orange-yellow / red-purple',
      fluorescence_lw:  'Weak red',
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 520, max: 700 },
      spectra:          ['RRUFF-R040025'],
    },

    color: {
      primary_color:          'Green (daylight) / Red (incandescent)',
      color_variants:         ['Teal-green', 'Purplish-red', 'Brownish-green'],
      dominant_wavelength_nm: 540,
      oklch:                  { l: 0.52, c: 0.18, h: 145 },
      hex:                    '#3a7d44',
      munsell:                '7.5GY 4/8',
      color_temperature_k:    null,
      psychological_effects:  ['Transformation', 'Duality', 'Adaptability', 'Luck'],
      harmonics: {
        complementary_hue: 325,
        triadic_hues:      [25, 265],
        analogous_range:   [125, 165],
      },
    },

    color_layer: 'natural',
    yin_yang_pair: 'yang',

    metaphysical: {
      mineral_name:     'Alexandrite',
      chakra_primary:   'Heart',
      chakra_secondary: ['Crown', 'Third Eye'],
      element:          ['Earth', 'Fire'],
      planet:           ['Mercury', 'Venus'],
      archetype:        ['The Shapeshifter', 'The Alchemist'],
      zodiac:           ['Gemini', 'Scorpio'],
      numerology:       5,
      angel_number:     555,
      intention:        'I embrace transformation. I hold both worlds within me.',
      traditions:       ['Vedic astrology', 'Crystal healing', 'Russian folk tradition'],
      properties:       [
        'Stone of duality — bridges apparent opposites',
        'Supports major life transitions and reinvention',
        'Enhances joy, luck, and serendipitous encounters',
        'Stimulates the imagination and creative intelligence',
        'June birthstone (modern)',
      ],
      gaia_resonance:   'QuantumNexus + SovereignCore',
      safety_warning:   null,
    },
  },

  // ── 3. Amazonite ──────────────────────────────────────────────────────────
  {
    name:        'Amazonite',
    trade_name:  false,
    mindat_id:   189,

    physical: {
      id:            189,
      longid:        'amazonite',
      guid:          '8b4g6c2d-5e3f-4g0b-c1d4-9e7f8g5h3c2d',
      name:          'Amazonite',
      ima_formula:   'KAlSi₃O₈',
      mindat_formula: 'KAlSi3O8',
      ima_status:    'A',
      ima_year:      1847,
      strunzten:     '9.FA.30',
      dana8ed:       '76.1.1.1',
      crystal_system: 'Triclinic',
      hardness_min:  6.0,
      hardness_max:  6.5,
      specific_gravity_min: 2.54,
      specific_gravity_max: 2.57,
      cleavage:      'Perfect on {001}, good on {010}',
      fracture:      'Uneven to splintery',
      tenacity:      'Brittle',
      luster:        ['Vitreous'],
      diaphaneity:   ['Translucent', 'Opaque'],
      colour:        'Blue-green to green, rarely white or grey',
      streak:        'White',
      fluorescence:  'Weak yellowish-white under LW UV',
      ri_min:        1.518,
      ri_max:        1.530,
      birefringence: 0.008,
      optical_type:  'B',
      shortdesc:     'Blue-green variety of microcline (potassium feldspar) coloured by trace Pb²⁺ and water.',
      updttime:      '2024-09-20T00:00:00Z',
      mindat_url:    'https://www.mindat.org/min-2621.html',
      piezoelectric:    false,
      safe_for_water:   false,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Amazonite',
      refractive_index: { n_alpha: 1.518, n_beta: 1.522, n_gamma: 1.530 },
      birefringence:    0.008,
      optical_sign:     '-',
      dispersion:       'Weak',
      pleochroism:      null,
      fluorescence_lw:  'Weak yellowish-white',
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 490, max: 530 },
      spectra:          [],
    },

    color: {
      primary_color:          'Blue-green',
      color_variants:         ['Teal', 'Turquoise-green', 'Pale blue', 'Mottled green-white'],
      dominant_wavelength_nm: 505,
      oklch:                  { l: 0.64, c: 0.12, h: 183 },
      hex:                    '#4db6ac',
      munsell:                '7.5BG 6/6',
      color_temperature_k:    null,
      psychological_effects:  ['Calm', 'Truth-speaking', 'Emotional balance', 'Hope'],
      harmonics: {
        complementary_hue: 3,
        triadic_hues:      [63, 303],
        analogous_range:   [163, 203],
      },
    },

    color_layer: 'natural',
    yin_yang_pair: 'yin',

    metaphysical: {
      mineral_name:     'Amazonite',
      chakra_primary:   'Heart',
      chakra_secondary: ['Throat'],
      element:          ['Water', 'Earth'],
      planet:           ['Uranus', 'Venus'],
      archetype:        ['The Peacemaker', 'The Truth-Teller'],
      zodiac:           ['Virgo', 'Aquarius', 'Aries'],
      numerology:       5,
      angel_number:     555,
      intention:        'I speak my truth with love. My heart and voice are aligned.',
      traditions:       ['Crystal healing', 'Native American tradition', 'Ancient Egyptian use'],
      properties:       [
        'Stone of truth, courage, and authentic communication',
        'Soothes emotional trauma and calms the nervous system',
        'Filters electromagnetic stress and geopathic stress',
        'Inspires integrity and setting healthy boundaries',
        'Supports manifestation of universal love',
      ],
      gaia_resonance:   'ViriditasHeart + ClarusLens',
      safety_warning:   'Not recommended for direct water elixirs — contains trace lead (Pb²⁺) responsible for colour. External use only.',
    },
  },

  // ── 4. Amber ──────────────────────────────────────────────────────────────
  {
    name:        'Amber',
    trade_name:  false,
    mindat_id:   208,

    physical: {
      id:            208,
      longid:        'amber',
      guid:          '9c5h7d3e-6f4g-4h1c-d2e5-0f8g9h6i4d3e',
      name:          'Amber',
      ima_formula:   'C₁₀H₁₆O + variable',
      mindat_formula: 'C10H16O',
      ima_status:    null,
      ima_year:      null,
      strunzten:     '10.AA.15',
      dana8ed:       null,
      crystal_system: 'Amorphous',
      hardness_min:  2.0,
      hardness_max:  2.5,
      specific_gravity_min: 1.05,
      specific_gravity_max: 1.10,
      cleavage:      null,
      fracture:      'Conchoidal',
      tenacity:      'Brittle',
      luster:        ['Resinous'],
      diaphaneity:   ['Transparent', 'Translucent', 'Opaque'],
      colour:        'Yellow, orange, brown, rarely blue, green, red',
      streak:        null,
      fluorescence:  'Bluish-white to yellowish under UV',
      ri_min:        1.539,
      ri_max:        1.545,
      birefringence: null,
      optical_type:  'Isotropic',
      shortdesc:     'Fossilised tree resin (mainly Baltic conifer). Organic gemstone up to 44 million years old.',
      updttime:      '2024-08-05T00:00:00Z',
      mindat_url:    'https://www.mindat.org/min-1802.html',
      piezoelectric:    false,
      safe_for_water:   false,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Amber',
      refractive_index: { n: 1.540 },
      birefringence:    null,
      optical_sign:     null,
      dispersion:       'Low',
      pleochroism:      null,
      fluorescence_lw:  'Bluish-white to yellowish',
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 570, max: 620 },
      spectra:          [],
    },

    color: {
      primary_color:          'Golden yellow',
      color_variants:         ['Orange', 'Cognac-brown', 'Honey', 'Lemon yellow', 'Rare blue/green'],
      dominant_wavelength_nm: 590,
      oklch:                  { l: 0.72, c: 0.16, h: 75 },
      hex:                    '#ffb300',
      munsell:                '5Y 7/10',
      color_temperature_k:    3000,
      psychological_effects:  ['Warmth', 'Vitality', 'Ancient wisdom', 'Protection', 'Joy'],
      harmonics: {
        complementary_hue: 255,
        triadic_hues:      [195, 315],
        analogous_range:   [55, 95],
      },
    },

    color_layer: 'natural',
    yin_yang_pair: 'yang',

    metaphysical: {
      mineral_name:     'Amber',
      chakra_primary:   'Solar Plexus',
      chakra_secondary: ['Sacral', 'Crown'],
      element:          ['Fire', 'Aether'],
      planet:           ['Sun'],
      archetype:        ['The Ancient One', 'The Preserver', 'The Healer'],
      zodiac:           ['Leo', 'Aquarius', 'Aries', 'Cancer'],
      numerology:       3,
      angel_number:     333,
      intention:        'I carry the light of ancient wisdom. Time is my teacher and protector.',
      traditions:       ['Baltic folk tradition', 'Ancient Greek (elektron)', 'Ayurveda', 'Norse tradition'],
      properties:       [
        'Ancient protector — absorbs negative energies and transmutes them',
        'Carries primordial life-force energy (insects, plant matter preserved within)',
        'Strong solar resonance — vitalises and warms the energy field',
        'Supports emotional healing, especially grief and ancestral wounds',
        'Electrostatic properties — one of the earliest-known sources of static electricity',
        'Traditional Baltic use: protection for children and teething (topical)',
      ],
      gaia_resonance:   'SovereignCore + Noosphere',
      safety_warning:   'Organic material — do not submerge in water; will absorb moisture, become brittle, and may release organic compounds. Topical/worn use only. Not for water elixirs.',
    },
  },

  // ── 5. Amethyst ───────────────────────────────────────────────────────────
  {
    name:        'Amethyst',
    trade_name:  false,
    mindat_id:   1062,

    physical: {
      id:            1062,
      longid:        'amethyst',
      guid:          '0d6i8e4f-7g5h-4i2d-e3f6-1g9h0i7j5e4f',
      name:          'Amethyst',
      ima_formula:   'SiO₂',
      mindat_formula: 'SiO2',
      ima_status:    'A',
      ima_year:      null,
      strunzten:     '4.DA.05',
      dana8ed:       '75.1.3.1',
      crystal_system: 'Trigonal',
      hardness_min:  7.0,
      hardness_max:  7.0,
      specific_gravity_min: 2.65,
      specific_gravity_max: 2.65,
      cleavage:      null,
      fracture:      'Conchoidal',
      tenacity:      'Brittle',
      luster:        ['Vitreous'],
      diaphaneity:   ['Transparent', 'Translucent'],
      colour:        'Violet to pale purple, sometimes reddish-purple',
      streak:        'White',
      fluorescence:  'None to weak UV response',
      ri_min:        1.544,
      ri_max:        1.553,
      birefringence: 0.009,
      optical_type:  'U',
      shortdesc:     'Purple variety of quartz coloured by Fe³⁺ irradiation centres. Most popular and widespread purple gemstone.',
      updttime:      '2024-12-01T00:00:00Z',
      mindat_url:    'https://www.mindat.org/min-198.html',
      piezoelectric:    true,
      safe_for_water:   true,
      safe_for_hardware: false,
    },

    optical: {
      mineral_name:     'Amethyst',
      refractive_index: { n_omega: 1.553, n_epsilon: 1.544 },
      birefringence:    0.009,
      optical_sign:     '-',
      dispersion:       '0.013',
      pleochroism:      'Weak: reddish-purple / bluish-violet',
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 390, max: 430 },
      spectra:          ['RRUFF-R040003'],
    },

    color: {
      primary_color:          'Violet',
      color_variants:         ['Pale lavender', 'Deep purple', 'Reddish-purple', 'Bicolor with citrine (ametrine)'],
      dominant_wavelength_nm: 410,
      oklch:                  { l: 0.52, c: 0.18, h: 308 },
      hex:                    '#9c27b0',
      munsell:                '7.5P 4/12',
      color_temperature_k:    null,
      psychological_effects:  ['Calm', 'Spiritual connection', 'Mental clarity', 'Sleep support', 'Sobriety'],
      harmonics: {
        complementary_hue: 128,
        triadic_hues:      [68, 188],
        analogous_range:   [288, 328],
      },
    },

    color_layer: 'natural',
    yin_yang_pair: 'yin',

    metaphysical: {
      mineral_name:     'Amethyst',
      chakra_primary:   'Crown',
      chakra_secondary: ['Third Eye'],
      element:          ['Air', 'Aether'],
      planet:           ['Jupiter', 'Saturn', 'Neptune'],
      archetype:        ['The Mystic', 'The Healer', 'The Sage'],
      zodiac:           ['Pisces', 'Virgo', 'Aquarius', 'Capricorn'],
      numerology:       3,
      angel_number:     333,
      intention:        'I open to the wisdom of the universe. My mind is clear, my spirit is awake.',
      traditions:       ['Western crystal healing', 'Greek myth (Dionysus)', 'Buddhist tradition', 'Chinese Feng Shui'],
      properties:       [
        'Master stone of spiritual awakening and psychic protection',
        'Calms the overactive mind; supports meditation and sleep',
        'Historically associated with sobriety (Greek: amethystos = not intoxicated)',
        'Strengthens intuition and connection to higher guidance',
        'Natural stress-reliever and emotional balancer',
      ],
      gaia_resonance:   'ClarusLens + SomnusVeil + Noosphere',
      safety_warning:   'Piezoelectric — keep away from sensitive electronics. Colour fades in prolonged direct sunlight (Fe³⁺ centres bleach). Water-safe for cleansing only; not for long-term immersion.',
    },
  },

];

export default BATCH_A4;
