/**
 * src/crystals/db/batch-c8b.data.ts
 * GAIA-OS Crystal Database — Batch C-8B
 *
 * Entries:
 *   1. Clinozoisite — epidote-group calcium aluminium sorosilicate
 *   2. Cobra Jasper — trade name jasper/chalcedony from India
 *   3. Colombianite — pseudotektite / volcanic glass from Colombia
 *   4. Conichalcite — calcium copper arsenate hydroxide; TOXIC
 *   5. Coquimbite — hydrated ferric sulfate; water-soluble / acidic
 *
 * Schema: CrystalRecord v1.3
 * Author: GAIA-OS Crystal Intelligence Engine
 * Date:   2026-05-31
 */

import type { CrystalRecord } from './crystal.schema';

const BATCH_C8B: CrystalRecord[] = [
  {
    name: 'Clinozoisite',
    mindat_id: 1087,
    rruff_ids: ['R050331'],
    last_synced: '2026-05-31T00:00:00Z',
    trade_name: false,
    color_layer: 'natural',
    yin_yang_pair: 'Epidote',
    physical: {
      id: 1087,
      longid: 'clinozoisite',
      guid: '',
      name: 'Clinozoisite',
      ima_formula: 'Ca₂Al₃(SiO₄)(Si₂O₇)O(OH)',
      mindat_formula: 'Ca2Al3(SiO4)(Si2O7)O(OH)',
      ima_status: 'A',
      ima_year: 1853,
      strunzten: '9.BG.05',
      dana8ed: '58.2.1.3',
      crystal_system: 'Monoclinic',
      hardness_min: 6.5,
      hardness_max: 7,
      specific_gravity_min: 3.25,
      specific_gravity_max: 3.38,
      cleavage: 'Perfect on {001}',
      fracture: 'Uneven to subconchoidal',
      tenacity: 'Brittle',
      luster: ['Vitreous'],
      diaphaneity: ['Transparent', 'Translucent'],
      colour: 'Colourless, pale grey, pale green, yellowish, rarely pink. Usually muted and understated compared with epidote.',
      streak: 'White',
      fluorescence: 'None to weak',
      ri_min: 1.706,
      ri_max: 1.724,
      birefringence: 0.011,
      optical_type: 'B',
      shortdesc: 'Clinozoisite — Ca₂Al₃(SiO₄)(Si₂O₇)O(OH), monoclinic epidote-group calcium aluminium sorosilicate. Al-dominant member of the clinozoisite–epidote series. H6.5–7, SG 3.25–3.38. Pale green to colourless.',
      updttime: '2026-05-31T00:00:00Z',
      mindat_url: 'https://www.mindat.org/min-1087.html',
      piezoelectric: false,
      safe_for_water: true,
      safe_for_hardware: false,
    },
    optical: {
      mineral_name: 'Clinozoisite',
      refractive_index: { n_alpha: 1.706, n_beta: 1.713, n_gamma: 1.724 },
      birefringence: 0.011,
      optical_sign: '+',
      dispersion: 'Moderate',
      pleochroism: 'Weak to none',
      fluorescence_lw: 'None to weak',
      fluorescence_sw: 'None',
      phosphorescence: null,
      visible_wavelength_nm: { min: 520, max: 560 },
      spectra: ['R050331'],
    },
    color: {
      primary_color: 'Pale grey-green to colourless',
      color_variants: [
        'Colourless',
        'Pale grey',
        'Pale green',
        'Yellowish green',
        'Rare pinkish tones',
      ],
      dominant_wavelength_nm: 540,
      oklch: { l: 0.78, c: 0.07, h: 145 },
      hex: '#b9c8b4',
      munsell: '5GY 7/2',
      color_temperature_k: null,
      psychological_effects: [
        'Its muted colour field creates a calm, low-drama visual presence.',
        'Clinozoisite often appears as a quietly supportive mineral rather than a showpiece.',
        'The pale green-grey palette suggests structural healing and equilibrium.',
      ],
      harmonics: {
        complementary_hue: 325,
        triadic_hues: [25, 265],
        analogous_range: [125, 165],
      },
    },
    metaphysical: {
      mineral_name: 'Clinozoisite',
      chakra_primary: 'Heart',
      chakra_secondary: ['Solar Plexus', 'Third Eye'],
      element: ['Earth', 'Water'],
      planet: ['Mercury', 'Venus'],
      archetype: ['The Restorer', 'The Quiet Corrector'],
      zodiac: ['Virgo', 'Taurus'],
      numerology: 4,
      angel_number: 444,
      intention: 'I restore balance by strengthening what is quiet, structural, and true.',
      traditions: [
        'Part of the epidote-group mineral family and commonly associated with metamorphic terranes.',
        'Historically treated as part of the broader epidote–zoisite–clinozoisite mineralogical conversation.',
        'Modern crystal use emphasizes repair, recalibration, and grounded renewal.',
      ],
      properties: [
        'Al-dominant member of the clinozoisite–epidote solid solution series.',
        'Common in regional and contact metamorphic rocks, calc-silicate rocks, skarns, and marbles.',
        'Safe for water; no major toxic elements in standard material.',
        'Hard enough for careful handling and cabinet display.',
      ],
      gaia_resonance: 'ViriditasHeart + AnchorPrism',
      safety_warning: 'Safe for water. No major toxic elements. Normal handling only.',
    },
  },
  {
    name: 'Cobra Jasper',
    mindat_id: null,
    rruff_ids: [],
    last_synced: '2026-05-31T00:00:00Z',
    trade_name: true,
    color_layer: 'natural',
    yin_yang_pair: 'Leopard Skin Jasper',
    physical: {
      id: null,
      longid: 'cobra-jasper',
      guid: '',
      name: 'Cobra Jasper (trade name jasper/chalcedony)',
      ima_formula: 'SiO₂',
      mindat_formula: 'SiO2',
      ima_status: 'Not IMA approved — trade name for patterned jasper/chalcedony material',
      ima_year: null,
      strunzten: '4.DA.05',
      dana8ed: '75.1.3.1',
      crystal_system: 'Trigonal (cryptocrystalline)',
      hardness_min: 6.5,
      hardness_max: 7,
      specific_gravity_min: 2.58,
      specific_gravity_max: 2.64,
      cleavage: 'None',
      fracture: 'Conchoidal to uneven',
      tenacity: 'Brittle',
      luster: ['Waxy', 'Dull'],
      diaphaneity: ['Opaque'],
      colour: 'Brown, tan, cream, red-brown, grey, black and white in sinuous patterns resembling scales, hoods, or desert camouflage.',
      streak: 'White',
      fluorescence: 'None',
      ri_min: 1.530,
      ri_max: 1.540,
      birefringence: 0.004,
      optical_type: 'U',
      shortdesc: 'Cobra Jasper — trade name for patterned jasper/chalcedony material from India. Opaque SiO₂ with serpentine-looking, scale-like or hood-like patterning. H6.5–7.',
      updttime: '2026-05-31T00:00:00Z',
      mindat_url: null,
      piezoelectric: false,
      safe_for_water: true,
      safe_for_hardware: false,
    },
    optical: {
      mineral_name: 'Cobra Jasper',
      refractive_index: { n_mean: 1.535 },
      birefringence: 0.004,
      optical_sign: '+',
      dispersion: 'Low',
      pleochroism: 'None',
      fluorescence_lw: 'None',
      fluorescence_sw: 'None',
      phosphorescence: null,
      visible_wavelength_nm: { min: 580, max: 620 },
      spectra: [],
    },
    color: {
      primary_color: 'Earthy brown and cream with reptilian patterning',
      color_variants: [
        'Tan and cream banded',
        'Red-brown and black mottled',
        'Grey-brown hooded patterns',
        'Cream with dark sinuous lines',
      ],
      dominant_wavelength_nm: 600,
      oklch: { l: 0.62, c: 0.10, h: 55 },
      hex: '#9d7452',
      munsell: '7.5YR 5/6',
      color_temperature_k: null,
      psychological_effects: [
        'The snake-like patterning creates alertness and instinctive attention.',
        'Its earthy palette grounds the dramatic visual motif in desert-like steadiness.',
        'The contrast between camouflage and ornament gives it a protective visual language.',
      ],
      harmonics: {
        complementary_hue: 235,
        triadic_hues: [175, 295],
        analogous_range: [35, 75],
      },
    },
    metaphysical: {
      mineral_name: 'Cobra Jasper',
      chakra_primary: 'Root',
      chakra_secondary: ['Solar Plexus', 'Sacral'],
      element: ['Earth', 'Fire'],
      planet: ['Mars', 'Saturn'],
      archetype: ['The Watcher', 'The Desert Guardian'],
      zodiac: ['Scorpio', 'Aries', 'Capricorn'],
      numerology: 8,
      angel_number: 808,
      intention: 'I stay alert, grounded, and difficult to deceive.',
      traditions: [
        'Marketed in modern crystal trade as a patterned jasper from India.',
        'Its naming is visual and commercial rather than mineralogically formal.',
        'Often grouped with animal-pattern jaspers used for grounding and protection symbolism.',
      ],
      properties: [
        'Trade name material; exact micro-impurity content varies by lot.',
        'Silica-based and generally durable.',
        'Safe for water under normal use.',
      ],
      gaia_resonance: 'AnchorPrism + SovereignCore',
      safety_warning: 'Safe for water. Standard silica handling only.',
    },
  },
  {
    name: 'Colombianite',
    mindat_id: 470723,
    rruff_ids: [],
    last_synced: '2026-05-31T00:00:00Z',
    trade_name: true,
    color_layer: 'natural',
    yin_yang_pair: 'Moldavite',
    physical: {
      id: 470723,
      longid: 'colombianite',
      guid: '',
      name: 'Colombianite (glass; pseudotektite / obsidian-like natural glass)',
      ima_formula: 'Variable natural silicate glass',
      mindat_formula: 'Natural glass',
      ima_status: 'Not IMA approved — natural glass / pseudotektite trade name',
      ima_year: null,
      strunzten: null,
      dana8ed: null,
      crystal_system: 'Amorphous',
      hardness_min: 5.5,
      hardness_max: 6,
      specific_gravity_min: 2.30,
      specific_gravity_max: 2.50,
      cleavage: 'None',
      fracture: 'Conchoidal',
      tenacity: 'Brittle',
      luster: ['Vitreous'],
      diaphaneity: ['Translucent', 'Opaque'],
      colour: 'Smoky grey, charcoal, black, sometimes olive-grey in transmitted light; often etched or weathered surface.',
      streak: 'White',
      fluorescence: 'None',
      ri_min: 1.48,
      ri_max: 1.52,
      birefringence: null,
      optical_type: null,
      shortdesc: 'Colombianite — natural glass from Colombia, commonly described as pseudotektite or obsidian-like volcanic glass; also called Piedra Rayo. Amorphous, smoky grey to black, H5.5–6.',
      updttime: '2026-05-31T00:00:00Z',
      mindat_url: 'https://www.mindat.org/min-470723.html',
      piezoelectric: false,
      safe_for_water: true,
      safe_for_hardware: false,
    },
    optical: {
      mineral_name: 'Colombianite',
      refractive_index: { n_mean: 1.50 },
      birefringence: null,
      optical_sign: null,
      dispersion: null,
      pleochroism: null,
      fluorescence_lw: 'None',
      fluorescence_sw: 'None',
      phosphorescence: null,
      visible_wavelength_nm: { min: 420, max: 700 },
      spectra: [],
    },
    color: {
      primary_color: 'Smoky charcoal-black natural glass',
      color_variants: [
        'Charcoal black',
        'Smoky grey',
        'Brown-black',
        'Olive-grey in transmitted light',
      ],
      dominant_wavelength_nm: null,
      oklch: { l: 0.30, c: 0.03, h: 250 },
      hex: '#404246',
      munsell: 'N 3/',
      color_temperature_k: null,
      psychological_effects: [
        'Its glassy darkness gives it an austere, sky-struck character.',
        'Weathered surfaces create a sense of age and impact even when its origin is debated.',
        'The translucent smoky edge softens the black mass with atmospheric depth.',
      ],
      harmonics: {
        complementary_hue: null,
        triadic_hues: null,
        analogous_range: null,
      },
    },
    metaphysical: {
      mineral_name: 'Colombianite',
      chakra_primary: 'Third Eye',
      chakra_secondary: ['Crown', 'Root'],
      element: ['Storm', 'Akasha', 'Fire'],
      planet: ['Uranus', 'Pluto'],
      archetype: ['The Lightning Stone', 'The Sky Glass'],
      zodiac: ['Aquarius', 'Scorpio'],
      numerology: 11,
      angel_number: 111,
      intention: 'I remember the strike, the shock, and the message carried in glass.',
      traditions: [
        'Known in trade as Piedra Rayo, or Lightning Stone, from Colombia.',
        'Often discussed as a pseudotektite rather than a true impact tektite.',
        'Associated in modern crystal culture with revelation, download, and rapid insight.',
      ],
      properties: [
        'Natural glass with ongoing debate around exact formation model, but generally treated as terrestrial pseudotektite / obsidian-like glass.',
        'Amorphous and brittle with conchoidal fracture.',
        'Safe for water under ordinary use; avoid thermal shock and impact.',
      ],
      gaia_resonance: 'QuantumNexus + ClarusLens + Noosphere',
      safety_warning: 'Safe for water. Brittle glass — avoid drops and temperature shock. Sharp edges possible.',
    },
  },
  {
    name: 'Conichalcite',
    mindat_id: 1118,
    rruff_ids: ['R050007'],
    last_synced: '2026-05-31T00:00:00Z',
    trade_name: false,
    color_layer: 'natural',
    yin_yang_pair: 'Adamite',
    physical: {
      id: 1118,
      longid: 'conichalcite',
      guid: '',
      name: 'Conichalcite',
      ima_formula: 'CaCu(AsO₄)(OH)',
      mindat_formula: 'CaCu(AsO4)(OH)',
      ima_status: 'A',
      ima_year: 1849,
      strunzten: '8.BH.35',
      dana8ed: '41.6.2.1',
      crystal_system: 'Orthorhombic',
      hardness_min: 4,
      hardness_max: 4.5,
      specific_gravity_min: 4.25,
      specific_gravity_max: 4.45,
      cleavage: 'Indistinct',
      fracture: 'Uneven to subconchoidal',
      tenacity: 'Brittle',
      luster: ['Vitreous', 'Resinous', 'Earthy'],
      diaphaneity: ['Transparent', 'Translucent', 'Opaque'],
      colour: 'Bright yellow-green to apple-green, often as botryoidal crusts or fibrous coatings.',
      streak: 'Greenish white',
      fluorescence: 'None',
      ri_min: 1.73,
      ri_max: 1.80,
      birefringence: 0.07,
      optical_type: 'B',
      shortdesc: 'Conichalcite — CaCu(AsO₄)(OH), orthorhombic calcium copper arsenate hydroxide. Bright apple-green secondary arsenate mineral. H4–4.5. TOXIC due to arsenic and copper.',
      updttime: '2026-05-31T00:00:00Z',
      mindat_url: 'https://www.mindat.org/min-1118.html',
      piezoelectric: false,
      safe_for_water: false,
      safe_for_hardware: false,
    },
    optical: {
      mineral_name: 'Conichalcite',
      refractive_index: { n_alpha: 1.73, n_beta: 1.77, n_gamma: 1.80 },
      birefringence: 0.07,
      optical_sign: '-',
      dispersion: 'Moderate',
      pleochroism: 'Weak green tones',
      fluorescence_lw: 'None',
      fluorescence_sw: 'None',
      phosphorescence: null,
      visible_wavelength_nm: { min: 540, max: 570 },
      spectra: ['R050007'],
    },
    color: {
      primary_color: 'Apple-green arsenate green',
      color_variants: [
        'Bright yellow-green',
        'Apple-green',
        'Olive-green',
        'Green botryoidal crusts',
      ],
      dominant_wavelength_nm: 555,
      oklch: { l: 0.72, c: 0.18, h: 135 },
      hex: '#83c34b',
      munsell: '5GY 7/8',
      color_temperature_k: null,
      psychological_effects: [
        'Its apple-green intensity is visually seductive in a way that hides its toxicity.',
        'Botryoidal growth gives it an almost biological surface language.',
        'The copper-arsenic chemistry creates a tension between beauty and warning.',
      ],
      harmonics: {
        complementary_hue: 315,
        triadic_hues: [15, 255],
        analogous_range: [115, 155],
      },
    },
    metaphysical: {
      mineral_name: 'Conichalcite',
      chakra_primary: 'Heart',
      chakra_secondary: ['Root'],
      element: ['Earth', 'Fire'],
      planet: ['Mars', 'Venus'],
      archetype: ['The Beautiful Warning', 'The Green Hazard'],
      zodiac: ['Scorpio', 'Virgo'],
      numerology: 5,
      angel_number: 555,
      intention: 'I reveal that beauty and danger can wear the same color.',
      traditions: [
        'Named in the 19th century from its cone-like forms and copper-lime chemistry.',
        'Collected as a vivid secondary mineral from oxidized ore zones.',
        'Modern use is strictly collector/display oriented because of arsenic risk.',
      ],
      properties: [
        'Secondary arsenate mineral forming in oxidized copper deposits.',
        'Often associated with adamite, olivenite, smithsonite, and calcite.',
        'Never use in water; avoid dust, licking, elixirs, and prolonged skin contact.',
      ],
      gaia_resonance: 'AnchorPrism + ClarusLens',
      safety_warning: '🚨 TOXIC — contains arsenic and copper. Never use in water. Do not ingest, inhale dust, or use for elixirs. Wash hands after handling.',
    },
  },
  {
    name: 'Coquimbite',
    mindat_id: 1130,
    rruff_ids: ['R050139'],
    last_synced: '2026-05-31T00:00:00Z',
    trade_name: false,
    color_layer: 'natural',
    yin_yang_pair: 'Halotrichite',
    physical: {
      id: 1130,
      longid: 'coquimbite',
      guid: '',
      name: 'Coquimbite',
      ima_formula: 'Fe₂(SO₄)₃·9H₂O',
      mindat_formula: 'Fe2(SO4)3·9H2O',
      ima_status: 'A',
      ima_year: 1841,
      strunzten: '7.CB.35',
      dana8ed: '29.6.9.1',
      crystal_system: 'Trigonal',
      hardness_min: 2,
      hardness_max: 2.5,
      specific_gravity_min: 2.05,
      specific_gravity_max: 2.15,
      cleavage: 'Perfect',
      fracture: 'Uneven',
      tenacity: 'Brittle',
      luster: ['Vitreous'],
      diaphaneity: ['Transparent', 'Translucent'],
      colour: 'White, pale violet, lilac, reddish-violet, yellowish white; often delicate and water-sensitive.',
      streak: 'White',
      fluorescence: 'None',
      ri_min: 1.53,
      ri_max: 1.57,
      birefringence: 0.04,
      optical_type: 'U',
      shortdesc: 'Coquimbite — Fe₂(SO₄)₃·9H₂O, trigonal hydrated ferric sulfate. Delicate lilac to white evaporitic or acid-mine-related sulfate mineral. H2–2.5. Water-soluble and acidic; not safe for water.',
      updttime: '2026-05-31T00:00:00Z',
      mindat_url: 'https://www.mindat.org/min-1130.html',
      piezoelectric: false,
      safe_for_water: false,
      safe_for_hardware: false,
    },
    optical: {
      mineral_name: 'Coquimbite',
      refractive_index: { n_omega: 1.57, n_epsilon: 1.53 },
      birefringence: 0.04,
      optical_sign: '-',
      dispersion: 'Weak',
      pleochroism: 'None to weak',
      fluorescence_lw: 'None',
      fluorescence_sw: 'None',
      phosphorescence: null,
      visible_wavelength_nm: { min: 400, max: 430 },
      spectra: ['R050139'],
    },
    color: {
      primary_color: 'Lilac-white hydrated sulfate pastel',
      color_variants: [
        'White',
        'Pale lilac',
        'Reddish violet',
        'Yellowish white',
      ],
      dominant_wavelength_nm: 410,
      oklch: { l: 0.86, c: 0.06, h: 315 },
      hex: '#d8cfe5',
      munsell: '10P 8/2',
      color_temperature_k: null,
      psychological_effects: [
        'Its pastel lilac appearance feels far gentler than its acidic chemistry.',
        'The delicacy of hydrated sulfate crystals creates an impression of fragility and ephemerality.',
        'It visually communicates impermanence: a mineral that does not want to remain exposed for long.',
      ],
      harmonics: {
        complementary_hue: 135,
        triadic_hues: [75, 195],
        analogous_range: [295, 335],
      },
    },
    metaphysical: {
      mineral_name: 'Coquimbite',
      chakra_primary: 'Crown',
      chakra_secondary: ['Third Eye'],
      element: ['Water', 'Air'],
      planet: ['Neptune', 'Moon'],
      archetype: ['The Dissolving Archive', 'The Fragile Salt Temple'],
      zodiac: ['Pisces', 'Cancer'],
      numerology: 7,
      angel_number: 707,
      intention: 'I teach that some structures are real even when they cannot endure contact.',
      traditions: [
        'Named for Coquimbo, Chile, where sulfate mineral assemblages helped define its identity.',
        'Commonly associated with acid sulfate environments, mine oxidation zones, and arid evaporitic settings.',
        'Collector interest centers on its color delicacy and rarity in stable display condition.',
      ],
      properties: [
        'Hydrated ferric sulfate mineral formed by oxidation and evaporation processes.',
        'Highly sensitive to humidity and liquid water.',
        'Should be kept dry, sealed when possible, and handled minimally.',
      ],
      gaia_resonance: 'Noosphere + ClarusLens',
      safety_warning: '⚠️ Not safe for water. Water-soluble and potentially acidic. Avoid humidity, soaking, and elixir use. Handle gently and keep dry.',
    },
  },
];

export default BATCH_C8B;
