/**
 * batch-a3.data.ts
 * BATCH A-3 | Alabaster · Alexandrite · Almandine Garnet · Amazonite · Amber
 * Added: 2026-05-29
 *
 * ⚠️  INTERPRETIVE / TRADITIONAL LAYER — NOT SCIENTIFIC DATA
 * Physics and mineral data sourced from IMA / Mindat conventions.
 * Metaphysical data sourced from established cross-cultural traditions.
 */

import type { CrystalRecord } from './crystal.schema';

export const BATCH_A3: CrystalRecord[] = [

  // ───────────────────────────────────────────────────────────────────────────
  // ALABASTER
  // ───────────────────────────────────────────────────────────────────────────
  {
    name:        'Alabaster',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: null,

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Alabaster',
      ima_formula:     'CaSO₄·2H₂O',
      mindat_formula:  'CaSO4·2H2O',
      ima_status:      null,
      ima_year:        null,
      strunzten:       null,
      dana8ed:         null,
      crystal_system:  'Monoclinic',
      hardness_min:    2.0,
      hardness_max:    2.0,
      specific_gravity_min: 2.30,
      specific_gravity_max: 2.35,
      cleavage:        'Perfect in one direction',
      fracture:        'Conchoidal',
      tenacity:        null,
      luster:          ['Waxy', 'Pearly'],
      diaphaneity:     ['Translucent', 'Opaque'],
      colour:          'White, cream, pale honey',
      streak:          'White',
      fluorescence:    'Weak cream-white under SW UV',
      ri_min:          1.520,
      ri_max:          1.530,
      birefringence:   0.010,
      optical_type:    'B',
      shortdesc:       'Fine-grained gypsum variety prized since antiquity for translucency and workability.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-1155.html',
    },

    optical: {
      mineral_name:       'Alabaster',
      refractive_index:   { n_alpha: 1.520, n_beta: 1.523, n_gamma: 1.530 },
      birefringence:      0.010,
      optical_sign:       '+',
      dispersion:         'Weak',
      pleochroism:        'None',
      fluorescence_lw:    null,
      fluorescence_sw:    'Weak cream-white',
      phosphorescence:    null,
      visible_wavelength_nm: null,
      spectra:            [],
    },

    color: {
      primary_color:          'White',
      color_variants:         ['White', 'Cream', 'Pale honey', 'Translucent'],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.96, c: 0.01, h: 90 },
      hex:                    '#f5f4ee',
      munsell:                null,
      color_temperature_k:    6500,
      psychological_effects:  [
        'Purity and sacred stillness',
        'Gentle illumination — full spectrum in potential',
        'Softens harsh mental states; invites receptivity',
      ],
      harmonics: {
        complementary_hue: null,
        triadic_hues:      null,
        analogous_range:   [60, 120],
      },
    },

    metaphysical: {
      mineral_name:     'Alabaster',
      chakra_primary:   'Crown',
      chakra_secondary: ['Third Eye', 'Higher Crown'],
      element:          ['Aether', 'Water'],
      planet:           ['Moon', 'Venus'],
      archetype:        ['Healer', 'Oracle', 'Mystic'],
      zodiac:           ['Cancer', 'Taurus', 'Capricorn'],
      numerology:       8,
      intention:        'Sacred stillness — divine light, peace, gentle purification',
      traditions:       [
        'Egyptian (temple vessels and canopic jars, 3000+ BCE)',
        'Italian Renaissance (religious sculpture)',
        'Mesopotamian (votive offerings)',
        'Modern Crystal Healing',
      ],
      properties: [
        'Physically transmits and diffuses light — used in temple lamps for millennia',
        'Brings deep peace, mental stillness, and access to inner knowing',
        'Gentle nervous system soother — excellent for anxiety and hypervigilance',
        'Connects to angelic realm and higher dimensional guidance',
        'Purifies spaces of meditation or prayer',
        'Extremely soft (Mohs 2) — do not submerge in water for extended periods',
      ],
      gaia_resonance:   'SomnusVeil — sacred stillness, temple light, nervous system soothing',
      safety_warning:   'Mohs 2 — fragile. Avoid water immersion (dissolves slowly). No elixirs.',
    },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // ALEXANDRITE
  // ───────────────────────────────────────────────────────────────────────────
  {
    name:        'Alexandrite',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: null,

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Alexandrite',
      ima_formula:     'BeAl₂O₄',
      mindat_formula:  'BeAl2O4',
      ima_status:      'A',
      ima_year:        null,
      strunzten:       '4.BA.05',
      dana8ed:         null,
      crystal_system:  'Orthorhombic',
      hardness_min:    8.5,
      hardness_max:    8.5,
      specific_gravity_min: 3.70,
      specific_gravity_max: 3.78,
      cleavage:        'Distinct in one direction',
      fracture:        'Conchoidal',
      tenacity:        'Brittle',
      luster:          ['Vitreous'],
      diaphaneity:     ['Transparent', 'Translucent'],
      colour:          'Green in daylight; red-purple in incandescent light',
      streak:          'White',
      fluorescence:    'Strong red under SW UV (chromium luminescence)',
      ri_min:          1.746,
      ri_max:          1.763,
      birefringence:   0.009,
      optical_type:    'B',
      shortdesc:       'Chromium-bearing chrysoberyl; world-renowned for dramatic color change between daylight and incandescent light.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-100.html',
    },

    optical: {
      mineral_name:    'Alexandrite',
      refractive_index: { n_alpha: 1.746, n_beta: 1.748, n_gamma: 1.763 },
      birefringence:   0.009,
      optical_sign:    '+',
      dispersion:      'Moderate',
      pleochroism:     'Strong trichroism: red, orange-yellow, green',
      fluorescence_lw: null,
      fluorescence_sw: 'Strong red (chromium)',
      phosphorescence: null,
      visible_wavelength_nm: { min: 520, max: 680 },
      spectra:         [],
    },

    color: {
      primary_color:          'Color-change (green/red)',
      color_variants:         ['Green (daylight)', 'Red-purple (incandescent)', 'Teal', 'Raspberry'],
      dominant_wavelength_nm: 530,
      oklch:                  { l: 0.45, c: 0.14, h: 145 },
      hex:                    '#2e7c4f',
      munsell:                null,
      color_temperature_k:    null,
      psychological_effects:  [
        'Green mode: growth, balance, heart healing',
        'Red mode: passion, vitality, root power',
        'The duality itself teaches paradox tolerance and identity integration',
      ],
      harmonics: {
        complementary_hue: 25,
        triadic_hues:      [265, 25],
        analogous_range:   [120, 180],
      },
    },

    metaphysical: {
      mineral_name:     'Alexandrite',
      chakra_primary:   'Heart',
      chakra_secondary: ['Crown', 'Root', 'Third Eye'],
      element:          ['Aether', 'Fire', 'Earth'],
      planet:           ['Mercury', 'Mars', 'Neptune'],
      archetype:        ['Alchemist', 'Sovereign', 'Oracle'],
      zodiac:           ['Scorpio', 'Gemini', 'Leo'],
      numerology:       5,
      intention:        'Integration of opposites — duality held in grace, transformation, adaptability',
      traditions:       [
        'Named for Tsar Alexander II (discovered ~1830 on his birthday, Ural Mts)',
        'Russian imperial stone — green and red = imperial military colours',
        'June birthstone (traditional)',
        'Modern Crystal Healing',
      ],
      properties: [
        'The only gemstone that is simultaneously its own complementary colour',
        'Chromium ions create dual-frequency absorption — physically embodies paradox',
        'Teaches that opposites are aspects of one truth — master stone of transformation',
        'Bridges Heart (green/love) and Root (red/survival) — integrates spiritual and physical',
        'Sharpens intuition for complex, paradoxical decisions',
        'Particularly powerful for identity transitions and major life changes',
        'Inspires self-confidence and optimism about the future',
      ],
      gaia_resonance:   'ClarusLens + SovereignCore — paradox integration, identity transformation, dual-spectrum clarity',
      safety_warning:   null,
    },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // ALMANDINE GARNET
  // ───────────────────────────────────────────────────────────────────────────
  {
    name:        'Almandine',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: null,

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Almandine',
      ima_formula:     'Fe₃Al₂(SiO₄)₃',
      mindat_formula:  'Fe3Al2(SiO4)3',
      ima_status:      'A',
      ima_year:        null,
      strunzten:       '9.AD.25',
      dana8ed:         null,
      crystal_system:  'Isometric',
      hardness_min:    7.0,
      hardness_max:    7.5,
      specific_gravity_min: 4.10,
      specific_gravity_max: 4.30,
      cleavage:        'None (indistinct)',
      fracture:        'Conchoidal to uneven',
      tenacity:        'Brittle',
      luster:          ['Vitreous', 'Resinous'],
      diaphaneity:     ['Transparent', 'Translucent'],
      colour:          'Deep red, dark red-brown, violet-red',
      streak:          'White',
      fluorescence:    'None (iron quenches fluorescence)',
      ri_min:          1.770,
      ri_max:          1.820,
      birefringence:   null,
      optical_type:    'I',
      shortdesc:       'Most abundant garnet species. Deep red iron-aluminum silicate. One of the oldest gem materials known.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-162.html',
    },

    optical: {
      mineral_name:    'Almandine',
      refractive_index: { n_omega: 1.790 },
      birefringence:   null,
      optical_sign:    null,
      dispersion:      'Moderate',
      pleochroism:     'None (isometric)',
      fluorescence_lw: null,
      fluorescence_sw: null,
      phosphorescence: null,
      visible_wavelength_nm: { min: 620, max: 680 },
      spectra:         [],
    },

    color: {
      primary_color:          'Deep red',
      color_variants:         ['Deep red', 'Dark red-brown', 'Violet-red', 'Burgundy'],
      dominant_wavelength_nm: 650,
      oklch:                  { l: 0.30, c: 0.20, h: 25 },
      hex:                    '#7a1a2e',
      munsell:                '5R 3/8',
      color_temperature_k:    1800,
      psychological_effects:  [
        'Primal vitality and deep passion',
        'Grounded life-force — the red of blood and earth\'s core',
        'Courage, devotion, and the will to survive and thrive',
      ],
      harmonics: {
        complementary_hue: 175,
        triadic_hues:      [145, 265],
        analogous_range:   [10, 40],
      },
    },

    metaphysical: {
      mineral_name:     'Almandine',
      chakra_primary:   'Root',
      chakra_secondary: ['Sacral', 'Heart'],
      element:          ['Earth', 'Fire'],
      planet:           ['Mars', 'Saturn', 'Earth'],
      archetype:        ['Warrior', 'Guardian', 'Sovereign'],
      zodiac:           ['Aries', 'Scorpio', 'Capricorn', 'Leo', 'Virgo'],
      numerology:       4,
      intention:        'Primal vitality — physical strength, grounded courage, life-force activation',
      traditions:       [
        'Egyptian (protective amulets, 3100 BCE)',
        'Roman (signet rings, military talismans)',
        'Medieval lapidary (Carbuncle — one of four primary gems)',
        'Hindu Ratna Shastra gem therapy',
        'Norse (placed in sword hilts)',
        'Western Esotericism',
      ],
      properties: [
        'Ancient stone of warriors — worn to ensure safe return from battle since 3100 BCE',
        'Powerfully activates Root Chakra and base life-force energy',
        'Regenerates and revitalises the physical body — supports stamina and vitality',
        'Grounds scattered or dissociated energy back into the physical form',
        'Strengthens survival instinct and the will to thrive',
        'Stone of devotion and commitment — deepens love and loyalty',
        'Protects against negativity at the physical-etheric boundary',
      ],
      gaia_resonance:   'AnchorPrism + SovereignCore — primal life-force, grounded warrior strength',
      safety_warning:   null,
    },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // AMAZONITE
  // ───────────────────────────────────────────────────────────────────────────
  {
    name:        'Amazonite',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: null,

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Amazonite',
      ima_formula:     'KAlSi₃O₈',
      mindat_formula:  'KAlSi3O8',
      ima_status:      null,
      ima_year:        null,
      strunzten:       '9.FA.30',
      dana8ed:         null,
      crystal_system:  'Triclinic',
      hardness_min:    6.0,
      hardness_max:    6.5,
      specific_gravity_min: 2.54,
      specific_gravity_max: 2.57,
      cleavage:        'Perfect in two directions',
      fracture:        'Uneven',
      tenacity:        'Brittle',
      luster:          ['Vitreous'],
      diaphaneity:     ['Opaque', 'Translucent'],
      colour:          'Turquoise, teal, mint green, pale aqua',
      streak:          'White',
      fluorescence:    'Weak green under LW UV',
      ri_min:          1.514,
      ri_max:          1.530,
      birefringence:   0.008,
      optical_type:    'B',
      shortdesc:       'Turquoise-green variety of microcline feldspar. Color from trace lead and water in crystal lattice.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-192.html',
    },

    optical: {
      mineral_name:    'Amazonite',
      refractive_index: { n_alpha: 1.514, n_beta: 1.522, n_gamma: 1.530 },
      birefringence:   0.008,
      optical_sign:    '-',
      dispersion:      'Weak',
      pleochroism:     'Weak',
      fluorescence_lw: 'Weak green',
      fluorescence_sw: null,
      phosphorescence: null,
      visible_wavelength_nm: { min: 480, max: 520 },
      spectra:         [],
    },

    color: {
      primary_color:          'Turquoise',
      color_variants:         ['Turquoise', 'Teal', 'Mint green', 'Blue-green', 'Pale aqua'],
      dominant_wavelength_nm: 495,
      oklch:                  { l: 0.70, c: 0.12, h: 185 },
      hex:                    '#6db8b0',
      munsell:                '5BG 7/4',
      color_temperature_k:    7500,
      psychological_effects:  [
        'Calm clarity at the intersection of thought (blue) and growth (green)',
        'Balanced communication — neither too sharp nor too soft',
        'Stillness of a turquoise lake — clear to the bottom',
      ],
      harmonics: {
        complementary_hue: 15,
        triadic_hues:      [305, 55],
        analogous_range:   [165, 210],
      },
    },

    metaphysical: {
      mineral_name:     'Amazonite',
      chakra_primary:   'Throat',
      chakra_secondary: ['Heart', 'Third Eye'],
      element:          ['Water', 'Earth'],
      planet:           ['Uranus', 'Venus', 'Mercury'],
      archetype:        ['Warrior', 'Healer', 'Creator'],
      zodiac:           ['Virgo', 'Aries', 'Leo', 'Scorpio'],
      numerology:       5,
      intention:        'Courageous truth — authentic voice, emotional boundaries, harmonious communication',
      traditions:       [
        'Ancient Egypt (found in Tutankhamun tomb, ~1323 BCE)',
        'Pre-Columbian Mesoamerica',
        'Named after Amazon River (association with warrior women)',
        'Western Esotericism',
        'Modern Crystal Healing',
      ],
      properties: [
        'Stone of truth, courage, and authentic self-expression',
        'Soothes emotional trauma and calms the nervous system',
        'Helps speak difficult truths with compassion and clarity',
        'Creates energetic boundaries without aggression',
        'Dissolves fear of judgment — encourages living by personal values',
        'Balances masculine and feminine energies in communication',
        'Powerful for those recovering their voice after suppression or trauma',
      ],
      gaia_resonance:   'SovereignCore + ViriditasHeart — authentic voice, courageous truth, emotional boundary clarity',
      safety_warning:   'Contains trace lead (chromophore). Safe to handle normally. Avoid water elixirs as a precaution. Wash hands after extended handling.',
    },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // AMBER
  // ───────────────────────────────────────────────────────────────────────────
  {
    name:        'Amber',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: null,

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Amber',
      ima_formula:     'C₁₀H₁₆O (approx.) + succinic acid',
      mindat_formula:  'C10H16O',
      ima_status:      null,
      ima_year:        null,
      strunzten:       '10.AA.05',
      dana8ed:         null,
      crystal_system:  'Amorphous',
      hardness_min:    2.0,
      hardness_max:    2.5,
      specific_gravity_min: 1.05,
      specific_gravity_max: 1.10,
      cleavage:        'None',
      fracture:        'Conchoidal',
      tenacity:        'Brittle',
      luster:          ['Resinous'],
      diaphaneity:     ['Transparent', 'Translucent', 'Opaque'],
      colour:          'Honey yellow, golden orange, cognac brown, pale lemon, cherry red, blue-green (rare)',
      streak:          'White',
      fluorescence:    'Strong blue-white to yellow-green under SW UV',
      ri_min:          1.539,
      ri_max:          1.545,
      birefringence:   null,
      optical_type:    null,
      shortdesc:       'Fossilised tree resin 30–100+ million years old. Gave electricity its name (Greek: elektron). Triboelectric.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-205.html',
    },

    optical: {
      mineral_name:    'Amber',
      refractive_index: { n_omega: 1.540 },
      birefringence:   null,
      optical_sign:    null,
      dispersion:      null,
      pleochroism:     'None',
      fluorescence_lw: 'Moderate blue-white',
      fluorescence_sw: 'Strong blue-white to yellow-green',
      phosphorescence: null,
      visible_wavelength_nm: { min: 560, max: 600 },
      spectra:         [],
    },

    color: {
      primary_color:          'Golden amber',
      color_variants:         [
        'Honey yellow', 'Golden orange', 'Cognac brown',
        'Pale lemon', 'Cherry red (rare)', 'Blue-green fluorescent (Dominican, rare)',
      ],
      dominant_wavelength_nm: 580,
      oklch:                  { l: 0.72, c: 0.18, h: 75 },
      hex:                    '#e8a820',
      munsell:                '5Y 7/10',
      color_temperature_k:    2700,
      psychological_effects:  [
        'Sunlight made solid — warmth, preserved life, solar joy',
        'Ancient comfort — bridges past and present through time',
        'Optimism and vitality without the harshness of raw fire',
      ],
      harmonics: {
        complementary_hue: 255,
        triadic_hues:      [195, 315],
        analogous_range:   [55, 95],
      },
    },

    metaphysical: {
      mineral_name:     'Amber',
      chakra_primary:   'Solar Plexus',
      chakra_secondary: ['Sacral', 'Throat', 'Root'],
      element:          ['Fire', 'Aether', 'Earth'],
      planet:           ['Sun', 'Mercury'],
      archetype:        ['Healer', 'Sage', 'Creator'],
      zodiac:           ['Leo', 'Aquarius', 'Aries', 'Gemini'],
      numerology:       3,
      intention:        'Ancient light — solar healing, purification, ancestral wisdom, life preserved in time',
      traditions:       [
        'Ancient Greece (elektron — source of the word electricity)',
        'Baltic peoples (tears of sun goddess Saule)',
        'Norse (Freya\'s tears)',
        'Roman (more valuable than slaves in certain periods)',
        'Native American',
        'Ayurvedic medicine (worn for warmth and vitality)',
        'Western Esotericism',
      ],
      properties: [
        'Fossilised tree resin 30–100 million years old — literally time made tangible',
        'Gave electricity its name — Greek elektron; rubbing generates triboelectric charge',
        'Carries memory of ancient forests, sunlight, and preserved life',
        'The original solar healing material — predates all crystal traditions',
        'Deeply purifying — absorbs pain and negativity without retaining it',
        'Brings warmth, optimism, and solar life-force to depleted systems',
        'Bridges past and present — integrates ancestral patterns and genetic memory',
        'Never needs cleansing — it is the purifier, not a receiver',
      ],
      gaia_resonance:   'SovereignCore + AnchorPrism — solar ancient light, ancestral memory, purification without depletion',
      safety_warning:   null,
    },
  },

];

export default BATCH_A3;
