/**
 * src/crystals/db/batch-a8.data.ts
 * GAIA-OS Crystal Database — Batch A-8
 *
 * Entries:
 *   1. Aurichalcite
 *   2. Aventurine
 *   3. Axinite
 *   4. Azurite in Quartz
 *   5. Azurite
 *
 * Schema: CrystalRecord v1.3
 * Author: GAIA-OS Crystal Intelligence Engine
 * Date:   2026-05-29
 */

import type { CrystalRecord } from './crystal.schema';

const BATCH_A8: CrystalRecord[] = [

  // ─────────────────────────────────────────────────────────────────────────
  // 1. AURICHALCITE
  // Copper-zinc carbonate hydroxide — robin's-egg blue-green — rare, fragile
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Aurichalcite',
    mindat_id:   430,
    rruff_ids:   ['R060225'],
    last_synced: '2026-05-29T00:00:00Z',
    trade_name:  false,
    color_layer: 'natural',
    yin_yang_pair: 'Carnelian',

    physical: {
      id:           430,
      longid:       'aurichalcite',
      guid:         '',
      name:         'Aurichalcite',
      ima_formula:  '(Zn,Cu)₅(CO₃)₂(OH)₆',
      mindat_formula: '(Zn,Cu)5(CO3)2(OH)6',
      ima_status:   'A',
      ima_year:     1839,
      strunzten:    '5.BA.10',
      dana8ed:      '16b.3.5.1',
      crystal_system: 'Orthorhombic',
      hardness_min: 1,
      hardness_max: 2,
      specific_gravity_min: 3.9,
      specific_gravity_max: 4.0,
      cleavage:    'Perfect on {010}',
      fracture:    'Uneven',
      tenacity:    'Brittle',
      luster:      ['Silky', 'Pearly'],
      diaphaneity: ['Translucent'],
      colour:      'Pale blue to blue-green',
      streak:      'Pale blue',
      fluorescence: null,
      ri_min:      1.655,
      ri_max:      1.909,
      birefringence: 0.254,
      optical_type: 'B',
      shortdesc:   'Rare copper-zinc carbonate hydroxide forming delicate acicular crystals in oxidised copper deposits.',
      updttime:    '2026-05-29T00:00:00Z',
      mindat_url:  'https://www.mindat.org/min-430.html',
      piezoelectric:    false,
      safe_for_water:   false,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name: 'Aurichalcite',
      refractive_index: { n_alpha: 1.655, n_beta: 1.675, n_gamma: 1.909 },
      birefringence:   0.254,
      optical_sign:    '-',
      dispersion:      'Strong',
      pleochroism:     'Trichroic: pale blue / greenish blue / colourless',
      fluorescence_lw: null,
      fluorescence_sw: null,
      phosphorescence: null,
      visible_wavelength_nm: { min: 470, max: 510 },
      spectra: ['R060225'],
    },

    color: {
      primary_color:          'Robin\'s-egg blue-green',
      color_variants:         ['Pale blue', 'Blue-green', 'Turquoise'],
      dominant_wavelength_nm: 490,
      oklch:   { l: 0.72, c: 0.09, h: 195 },
      hex:     '#7ecfce',
      munsell: '5BG 7/4',
      color_temperature_k:    9500,
      psychological_effects:  [
        'Gentle calming — softer and more yielding than Azurite',
        'Emotional tenderness and vulnerability',
        'Cooling, anti-inflammatory visual frequency',
        'Encourages quiet introspection and peaceful communication',
      ],
      harmonics: {
        complementary_hue: 15,
        triadic_hues:      [315, 75],
        analogous_range:   [175, 215],
      },
    },

    metaphysical: {
      mineral_name:     'Aurichalcite',
      chakra_primary:   'Throat',
      chakra_secondary: ['Heart'],
      element:   ['Water', 'Air'],
      planet:    ['Venus', 'Neptune'],
      archetype: ['The Healer', 'The Messenger'],
      zodiac:    ['Aquarius', 'Libra'],
      numerology: 6,
      angel_number: 555,
      intention: 'Speak from the heart with gentleness and truth.',
      traditions: ['Western crystal healing', 'Colour therapy'],
      properties: [
        'Rare and fragile — its delicacy mirrors the sensitivity it invites',
        'Supports gentle truth-telling and compassionate communication',
        'Assists emotional healing within relationships',
        'Copper component activates heart-throat axis',
        'Useful in dream-state communication and channelling clarity',
      ],
      gaia_resonance: 'ViriditasHeart + SomnusVeil',
      safety_warning: 'Contains copper and zinc — toxic if ingested. Not safe for water elixirs. Handle with care — very fragile crystals.',
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 2. AVENTURINE
  // Quartz with fuchsite inclusions — green sparkle — abundance stone
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Aventurine',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: '2026-05-29T00:00:00Z',
    trade_name:  true,
    color_layer: 'natural',
    yin_yang_pair: 'Red Jasper',

    physical: {
      id:           0,
      longid:       'aventurine',
      guid:         '',
      name:         'Quartz (Aventurine variety)',
      ima_formula:  'SiO₂',
      mindat_formula: 'SiO2',
      ima_status:   'A',
      ima_year:     null,
      strunzten:    '4.DA.05',
      dana8ed:      '75.1.3.1',
      crystal_system: 'Trigonal',
      hardness_min: 6.5,
      hardness_max: 7,
      specific_gravity_min: 2.64,
      specific_gravity_max: 2.69,
      cleavage:    'None',
      fracture:    'Conchoidal',
      tenacity:    'Brittle',
      luster:      ['Vitreous', 'Waxy'],
      diaphaneity: ['Translucent', 'Opaque'],
      colour:      'Green (most common), also orange, blue, red, yellow',
      streak:      'White',
      fluorescence: null,
      ri_min:      1.544,
      ri_max:      1.553,
      birefringence: 0.009,
      optical_type: 'U',
      shortdesc:   'Translucent quartz variety with aventurescence caused by fuchsite, hematite, or other platelet inclusions.',
      updttime:    '2026-05-29T00:00:00Z',
      mindat_url:  'https://www.mindat.org/min-29165.html',
      piezoelectric:    true,
      safe_for_water:   true,
      safe_for_hardware: false,
    },

    optical: {
      mineral_name: 'Aventurine',
      refractive_index: { n_omega: 1.553, n_epsilon: 1.544 },
      birefringence:   0.009,
      optical_sign:    '-',
      dispersion:      null,
      pleochroism:     'Weak',
      fluorescence_lw: null,
      fluorescence_sw: null,
      phosphorescence: null,
      visible_wavelength_nm: { min: 500, max: 570 },
      spectra: [],
    },

    color: {
      primary_color:          'Aventurine green',
      color_variants:         ['Pale green', 'Mid green', 'Deep forest green', 'Blue aventurine', 'Orange aventurine'],
      dominant_wavelength_nm: 535,
      oklch:   { l: 0.62, c: 0.12, h: 145 },
      hex:     '#6aad7a',
      munsell: '5G 6/4',
      color_temperature_k:    null,
      psychological_effects:  [
        'Growth, optimism, and forward momentum',
        'Abundance consciousness — the green of new leaves and opportunity',
        'Calms nervous system while energising the will',
        'Associated with luck, prosperity, and open-hearted confidence',
      ],
      harmonics: {
        complementary_hue: 325,
        triadic_hues:      [265, 25],
        analogous_range:   [125, 165],
      },
    },

    metaphysical: {
      mineral_name:     'Aventurine',
      chakra_primary:   'Heart',
      chakra_secondary: ['Solar Plexus'],
      element:   ['Earth', 'Water'],
      planet:    ['Venus', 'Mercury'],
      archetype: ['The Gambler', 'The Gardener', 'The Opportunist'],
      zodiac:    ['Aries', 'Taurus', 'Libra'],
      numerology: 3,
      angel_number: 444,
      intention: 'I am open to abundance, growth, and the best possible outcome.',
      traditions: ['Western crystal healing', 'Feng Shui', 'Vedic gemology'],
      properties: [
        'The classic abundance and luck stone — widely used in prosperity grids',
        'Green aventurine activates heart chakra while grounding optimism in the body',
        'Fuchsite inclusions add the healer\'s vibration — compassion in action',
        'Useful for releasing old patterns and embracing new beginnings',
        'Supports athletes, gamblers, and anyone embracing risk toward growth',
      ],
      gaia_resonance: 'ViriditasHeart + SovereignCore',
      safety_warning: null,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 3. AXINITE
  // Calcium aluminium borosilicate — brown-violet — rare, complex
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Axinite',
    mindat_id:   459,
    rruff_ids:   ['R050020', 'R050021'],
    last_synced: '2026-05-29T00:00:00Z',
    trade_name:  false,
    color_layer: 'natural',
    yin_yang_pair: 'Aquamarine',

    physical: {
      id:           459,
      longid:       'axinite',
      guid:         '',
      name:         'Axinite-(Fe)',
      ima_formula:  'Ca₂Fe²⁺Al₂BSi₄O₁₅(OH)',
      mindat_formula: 'Ca2FeAl2BSi4O15(OH)',
      ima_status:   'A',
      ima_year:     1797,
      strunzten:    '9.BJ.10',
      dana8ed:      '58.1.1.1',
      crystal_system: 'Triclinic',
      hardness_min: 6.5,
      hardness_max: 7,
      specific_gravity_min: 3.26,
      specific_gravity_max: 3.36,
      cleavage:    'Good on {100}, distinct on {001} and {110}',
      fracture:    'Conchoidal to uneven',
      tenacity:    'Brittle',
      luster:      ['Vitreous'],
      diaphaneity: ['Transparent', 'Translucent'],
      colour:      'Clove-brown, violet-brown, grey, yellow',
      streak:      'White',
      fluorescence: 'Weak orange under LW UV',
      ri_min:      1.672,
      ri_max:      1.694,
      birefringence: 0.012,
      optical_type: 'B',
      shortdesc:   'Triclinic borosilicate forming sharp axe-head crystals in contact-metamorphic zones. Strongly trichroic.',
      updttime:    '2026-05-29T00:00:00Z',
      mindat_url:  'https://www.mindat.org/min-459.html',
      piezoelectric:    false,
      safe_for_water:   true,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name: 'Axinite',
      refractive_index: { n_alpha: 1.672, n_beta: 1.682, n_gamma: 1.694 },
      birefringence:   0.012,
      optical_sign:    '-',
      dispersion:      'Strong 0.018–0.020',
      pleochroism:     'Strongly trichroic: clove-brown / violet / pale yellow',
      fluorescence_lw: 'Weak orange',
      fluorescence_sw: null,
      phosphorescence: null,
      visible_wavelength_nm: { min: 400, max: 620 },
      spectra: ['R050020', 'R050021'],
    },

    color: {
      primary_color:          'Clove-brown with violet undertones',
      color_variants:         ['Brown', 'Violet-brown', 'Golden yellow', 'Grey-violet'],
      dominant_wavelength_nm: 585,
      oklch:   { l: 0.38, c: 0.07, h: 42 },
      hex:     '#7a5530',
      munsell: '7.5YR 3/4',
      color_temperature_k:    3200,
      psychological_effects:  [
        'Grounding with a layer of mystery — the brown-violet creates unusual depth',
        'Encourages patient endurance through complex situations',
        'Stabilising without being heavy — the triclinic asymmetry mirrors adaptability',
        'Associated with ancestral memory and deep earth wisdom',
      ],
      harmonics: {
        complementary_hue: 222,
        triadic_hues:      [162, 282],
        analogous_range:   [22, 62],
      },
    },

    metaphysical: {
      mineral_name:     'Axinite',
      chakra_primary:   'Root',
      chakra_secondary: ['Sacral', 'Third Eye'],
      element:   ['Earth', 'Fire'],
      planet:    ['Saturn', 'Pluto'],
      archetype: ['The Elder', 'The Deep Keeper'],
      zodiac:    ['Capricorn', 'Aries'],
      numerology: 8,
      angel_number: 444,
      intention: 'I root into the ancient earth and draw on its enduring strength.',
      traditions: ['Western crystal healing', 'Earth mysteries tradition'],
      properties: [
        'Named for its axe-head crystal habit — a stone of cutting through illusion',
        'Strongly grounding while stimulating third eye awareness simultaneously',
        'Supports endurance, stamina, and long-term focus on complex goals',
        'Trichroic nature reflects the capacity to see a situation from three angles',
        'Used in ancestral healing and past-life excavation work',
      ],
      gaia_resonance: 'AnchorPrism + ClarusLens',
      safety_warning: null,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 4. AZURITE IN QUARTZ
  // Azurite inclusions in quartz matrix — dual-layer resonance
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Azurite in Quartz',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: '2026-05-29T00:00:00Z',
    trade_name:  true,
    color_layer: 'natural',
    yin_yang_pair: 'Sunstone',

    physical: {
      id:           0,
      longid:       'azurite-in-quartz',
      guid:         '',
      name:         'Azurite + Quartz (composite)',
      ima_formula:  'Cu₃(CO₃)₂(OH)₂ in SiO₂',
      mindat_formula: 'Cu3(CO3)2(OH)2 in SiO2',
      ima_status:   null,
      ima_year:     null,
      strunzten:    null,
      dana8ed:      null,
      crystal_system: 'Trigonal',
      hardness_min: 3.5,
      hardness_max: 7,
      specific_gravity_min: 2.65,
      specific_gravity_max: 3.77,
      cleavage:    'None (quartz dominant); azurite inclusions may show perfect cleavage',
      fracture:    'Conchoidal',
      tenacity:    'Brittle',
      luster:      ['Vitreous', 'Adamantine'],
      diaphaneity: ['Translucent', 'Opaque'],
      colour:      'Deep blue azurite in white to grey quartz matrix',
      streak:      'Blue on azurite; white on quartz',
      fluorescence: null,
      ri_min:      1.544,
      ri_max:      1.838,
      birefringence: null,
      optical_type: null,
      shortdesc:   'Trade name for specimens of azurite growing within or included in quartz matrix. Combines quartz amplification with azurite\'s deep indigo frequency.',
      updttime:    '2026-05-29T00:00:00Z',
      mindat_url:  null,
      piezoelectric:    true,
      safe_for_water:   false,
      safe_for_hardware: false,
    },

    optical: {
      mineral_name: 'Azurite in Quartz',
      refractive_index: { n_omega: 1.553, n_epsilon: 1.544 },
      birefringence:   null,
      optical_sign:    null,
      dispersion:      null,
      pleochroism:     'Azurite component: strongly trichroic blue/violet/colourless',
      fluorescence_lw: null,
      fluorescence_sw: null,
      phosphorescence: null,
      visible_wavelength_nm: { min: 420, max: 490 },
      spectra: [],
    },

    color: {
      primary_color:          'Deep cerulean blue on white-grey matrix',
      color_variants:         ['Deep indigo blue', 'Royal blue', 'Blue-white contrast'],
      dominant_wavelength_nm: 455,
      oklch:   { l: 0.42, c: 0.18, h: 258 },
      hex:     '#2244a8',
      munsell: '7.5PB 3/10',
      color_temperature_k:    null,
      psychological_effects:  [
        'Amplified clarity — quartz magnifies azurite\'s third eye activation',
        'Deep indigo blue opens the visionary mind while keeping it clear and coherent',
        'The white matrix provides contrast — insight against stillness',
        'Powerful for meditation, visioning, and inner-plane communication',
      ],
      harmonics: {
        complementary_hue: 78,
        triadic_hues:      [18, 138],
        analogous_range:   [238, 278],
      },
    },

    metaphysical: {
      mineral_name:     'Azurite in Quartz',
      chakra_primary:   'Third Eye',
      chakra_secondary: ['Crown', 'Throat'],
      element:   ['Water', 'Air', 'Aether'],
      planet:    ['Jupiter', 'Uranus'],
      archetype: ['The Visionary', 'The Seer', 'The Oracle'],
      zodiac:    ['Sagittarius', 'Aquarius', 'Pisces'],
      numerology: 9,
      angel_number: 777,
      intention: 'The quartz amplifies what the azurite reveals — I see with perfect clarity.',
      traditions: ['Western crystal healing', 'Ceremonial visioning'],
      properties: [
        'Dual-layer resonance: azurite\'s deep vision amplified by quartz\'s programmable clarity',
        'Exceptional for meditation and third eye activation',
        'Quartz matrix stabilises the intensity of azurite\'s psychic opening',
        'Supports clear channelling, dream clarity, and inner plane communication',
        'The contrast of deep blue in white stone embodies the seeing mind within stillness',
      ],
      gaia_resonance: 'ClarusLens + Noosphere + QuantumNexus',
      safety_warning: 'Contains copper carbonate (azurite component) — toxic if ingested. Not safe for water elixirs or direct skin contact for extended periods. Piezoelectric via quartz — keep away from sensitive hardware.',
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 5. AZURITE
  // Copper carbonate hydroxide — the deepest blue in the mineral world
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Azurite',
    mindat_id:   474,
    rruff_ids:   ['R050400', 'R050401', 'R060400'],
    last_synced: '2026-05-29T00:00:00Z',
    trade_name:  false,
    color_layer: 'natural',
    yin_yang_pair: 'Citrine',

    physical: {
      id:           474,
      longid:       'azurite',
      guid:         '',
      name:         'Azurite',
      ima_formula:  'Cu₃(CO₃)₂(OH)₂',
      mindat_formula: 'Cu3(CO3)2(OH)2',
      ima_status:   'A',
      ima_year:     1824,
      strunzten:    '5.BA.05',
      dana8ed:      '16b.3.1.1',
      crystal_system: 'Monoclinic',
      hardness_min: 3.5,
      hardness_max: 4,
      specific_gravity_min: 3.77,
      specific_gravity_max: 3.89,
      cleavage:    'Perfect on {011}, good on {100}',
      fracture:    'Conchoidal',
      tenacity:    'Brittle',
      luster:      ['Vitreous', 'Adamantine'],
      diaphaneity: ['Transparent', 'Translucent'],
      colour:      'Azure blue — the defining copper blue',
      streak:      'Light blue',
      fluorescence: null,
      ri_min:      1.730,
      ri_max:      1.838,
      birefringence: 0.108,
      optical_type: 'B',
      shortdesc:   'Vivid blue copper carbonate hydroxide forming in oxidised copper ore zones. One of the most intensely coloured blue minerals known.',
      updttime:    '2026-05-29T00:00:00Z',
      mindat_url:  'https://www.mindat.org/min-474.html',
      piezoelectric:    false,
      safe_for_water:   false,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name: 'Azurite',
      refractive_index: { n_alpha: 1.730, n_beta: 1.758, n_gamma: 1.838 },
      birefringence:   0.108,
      optical_sign:    '+',
      dispersion:      'Strong',
      pleochroism:     'Strongly trichroic: deep blue / violet-blue / pale blue',
      fluorescence_lw: null,
      fluorescence_sw: null,
      phosphorescence: null,
      visible_wavelength_nm: { min: 420, max: 480 },
      spectra: ['R050400', 'R050401', 'R060400'],
    },

    color: {
      primary_color:          'Azure — deep copper blue',
      color_variants:         ['Deep royal blue', 'Violet-blue', 'Cerulean', 'Indigo'],
      dominant_wavelength_nm: 450,
      oklch:   { l: 0.35, c: 0.22, h: 255 },
      hex:     '#1a2e9e',
      munsell: '7.5PB 2/10',
      color_temperature_k:    null,
      psychological_effects:  [
        'One of the most psychically activating blue-violet frequencies in mineralogy',
        'Opens the third eye and deepens meditative depth rapidly',
        'Deep, saturated blue triggers the most inward-facing, contemplative states',
        'Associated with wisdom, truth, inner knowledge, and the Akashic field',
        'High chroma at low lightness creates an almost gravitational visual pull inward',
      ],
      harmonics: {
        complementary_hue: 75,
        triadic_hues:      [15, 135],
        analogous_range:   [235, 275],
      },
    },

    metaphysical: {
      mineral_name:     'Azurite',
      chakra_primary:   'Third Eye',
      chakra_secondary: ['Crown', 'Throat'],
      element:   ['Water', 'Air'],
      planet:    ['Jupiter', 'Saturn'],
      archetype: ['The Oracle', 'The Sage', 'The Akashic Librarian'],
      zodiac:    ['Sagittarius', 'Aquarius', 'Capricorn'],
      numerology: 1,
      angel_number: 777,
      intention: 'I access the deepest wisdom within and read the field with clarity.',
      traditions: [
        'Ancient Egyptian mystery schools',
        'Aztec ceremonial tradition',
        'Atlantean / Lemurian metaphysical tradition',
        'Western crystal healing',
        'Alchemical tradition — lapis lazuli predecessor pigment',
      ],
      properties: [
        'The master stone of the third eye — most intensely blue crystal in common use',
        'Used by ancient Egyptian priests as sacred pigment and ceremonial stone',
        'Strongly activates clairvoyance, psychic vision, and meditative depth',
        'Accelerates spiritual development — not recommended for beginners without grounding',
        'Often found with Malachite — the pairing of vision (Azurite) and heart (Malachite)',
        'The Akashic librarian — facilitates access to deep inner knowing and past-life memory',
        'High copper content activates nervous system sensitivity and psychic receptivity',
      ],
      gaia_resonance: 'ClarusLens + Noosphere + SomnusVeil',
      safety_warning: 'Contains copper carbonate — TOXIC if ingested or inhaled as dust. Never use for water elixirs. Wash hands after handling. Do not polish without respiratory protection. Safe for grids and display.',
    },
  },

];

export default BATCH_A8;
