/**
 * src/crystals/db/batch-b3.data.ts
 * GAIA-OS Crystal Database — Batch B-3
 *
 * Entries:
 *   1. Black Chalcedony
 *   2. Black Kyanite
 *   3. Black Moonstone
 *   4. Black Obsidian
 *   5. Black Onyx
 *
 * Schema: CrystalRecord v1.3
 */

import type { CrystalRecord } from './crystal.schema';

export const BATCH_B3: CrystalRecord[] = [

  // ── 1. Black Chalcedony ───────────────────────────────────────────────────────
  {
    name:        'Black Chalcedony',
    trade_name:  false,
    mindat_id:   3424,

    physical: {
      id:            3424,
      longid:        'black-chalcedony',
      guid:          'f1a2b3c4-d5e6-7890-abcd-ef1234567890',
      name:          'Black Chalcedony',
      ima_formula:   'SiO₂',
      mindat_formula: 'SiO2',
      ima_status:    'A',
      ima_year:      null,
      strunzten:     '4.DA.05',
      dana8ed:       '75.1.3.1',
      crystal_system: 'Trigonal (cryptocrystalline)',
      hardness_min:  6.5,
      hardness_max:  7.0,
      specific_gravity_min: 2.58,
      specific_gravity_max: 2.64,
      cleavage:      null,
      fracture:      'Conchoidal',
      tenacity:      'Tough to brittle',
      luster:        ['Waxy', 'Dull'],
      diaphaneity:   ['Translucent', 'Opaque'],
      colour:        'Black to blue-black, dark grey',
      streak:        'White',
      fluorescence:  null,
      ri_min:        1.530,
      ri_max:        1.540,
      birefringence: 0.004,
      optical_type:  'U',
      shortdesc:     'Dark to black variety of chalcedony (microcrystalline quartz). Colour from carbon or organic inclusions.',
      updttime:      '2024-11-20T00:00:00Z',
      mindat_url:    'https://www.mindat.org/min-954.html',
      piezoelectric:    false,
      safe_for_water:   true,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Black Chalcedony',
      refractive_index: { n_omega: 1.539, n_epsilon: 1.530 },
      birefringence:    0.004,
      optical_sign:     '-',
      dispersion:       'Weak',
      pleochroism:      null,
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: null,
      spectra:          [],
    },

    color: {
      primary_color:          'Black',
      color_variants:         ['Blue-black', 'Dark grey', 'Charcoal'],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.14, c: 0.02, h: 250 },
      hex:                    '#1c1c2e',
      munsell:                'N 1.5/',
      color_temperature_k:    null,
      psychological_effects:  ['Protection', 'Stillness', 'Depth', 'Quiet strength'],
      harmonics: {
        complementary_hue: null,
        triadic_hues:      null,
        analogous_range:   null,
      },
    },

    color_layer: 'natural',
    yin_yang_pair: 'yin',

    metaphysical: {
      mineral_name:     'Black Chalcedony',
      chakra_primary:   'Root',
      chakra_secondary: ['Throat', 'Third Eye'],
      element:          ['Earth', 'Water'],
      planet:           ['Saturn', 'Moon'],
      archetype:        ['The Protector', 'The Silent Guardian'],
      zodiac:           ['Scorpio', 'Capricorn'],
      numerology:       8,
      angel_number:     888,
      intention:        'I am guarded in silence. My stillness is my fortress.',
      traditions:       ['Crystal healing', 'Amulet tradition (Mediterranean)'],
      properties:       [
        'Strong protective stone absorbing negative energies',
        'Promotes quiet inner strength and emotional resilience',
        'Shields the aura from psychic interference',
        'Supports integration of shadow aspects',
        'Calming yet grounding — eases anxiety and overthinking',
      ],
      gaia_resonance:   'SovereignCore + ChthonField',
      safety_warning:   null,
    },
  },

  // ── 2. Black Kyanite ──────────────────────────────────────────────────────────
  {
    name:        'Black Kyanite',
    trade_name:  false,
    mindat_id:   2215,

    physical: {
      id:            2215,
      longid:        'black-kyanite',
      guid:          'a2b3c4d5-e6f7-8901-bcde-f12345678901',
      name:          'Black Kyanite',
      ima_formula:   'Al₂SiO₅',
      mindat_formula: 'Al2SiO5',
      ima_status:    'A',
      ima_year:      1789,
      strunzten:     '9.AF.20',
      dana8ed:       '52.3.1.1',
      crystal_system: 'Triclinic',
      hardness_min:  4.5,
      hardness_max:  7.0,
      specific_gravity_min: 3.53,
      specific_gravity_max: 3.70,
      cleavage:      'Perfect on {100}',
      fracture:      'Splintery',
      tenacity:      'Brittle',
      luster:        ['Vitreous', 'Pearly on cleavage'],
      diaphaneity:   ['Translucent', 'Opaque'],
      colour:        'Black to dark grey, sometimes with metallic lustre',
      streak:        'White',
      fluorescence:  null,
      ri_min:        1.712,
      ri_max:        1.734,
      birefringence: 0.017,
      optical_type:  'B',
      shortdesc:     'Black variety of kyanite (aluminium silicate). Anisotropic hardness: 4.5 on {100}, 6–7 on {010}. Fan-blade crystal habit.',
      updttime:      '2024-10-08T00:00:00Z',
      mindat_url:    'https://www.mindat.org/min-2215.html',
      piezoelectric:    false,
      safe_for_water:   false,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Black Kyanite',
      refractive_index: { n_alpha: 1.712, n_beta: 1.720, n_gamma: 1.734 },
      birefringence:    0.017,
      optical_sign:     '-',
      dispersion:       'Moderate',
      pleochroism:      null,
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: null,
      spectra:          [],
    },

    color: {
      primary_color:          'Black',
      color_variants:         ['Dark grey', 'Charcoal with silver sheen', 'Blue-black'],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.15, c: 0.01, h: 240 },
      hex:                    '#1a1a2a',
      munsell:                'N 1.5/',
      color_temperature_k:    null,
      psychological_effects:  ['Deep grounding', 'Cord-cutting', 'Auric clearing', 'Protection'],
      harmonics: {
        complementary_hue: null,
        triadic_hues:      null,
        analogous_range:   null,
      },
    },

    color_layer: 'natural',
    yin_yang_pair: 'yin',

    metaphysical: {
      mineral_name:     'Black Kyanite',
      chakra_primary:   'Root',
      chakra_secondary: ['Earth Star', 'All chakras (clearing)'],
      element:          ['Earth', 'Aether'],
      planet:           ['Saturn', 'Pluto'],
      archetype:        ['The Cord-Cutter', 'The Auric Surgeon'],
      zodiac:           ['Aries', 'Taurus', 'Libra'],
      numerology:       9,
      angel_number:     999,
      intention:        'I release all that no longer serves. My energy field is clear, sovereign, and whole.',
      traditions:       ['Crystal healing', 'Energy work'],
      properties:       [
        'Powerful cord-cutting and auric clearing stone',
        'Never needs cleansing — does not accumulate negative energy',
        'Aligns all chakras simultaneously without conscious direction',
        'Fan-blade form used to sweep and seal the aura',
        'Deep grounding; connects to Earth Star chakra below the feet',
        'Supports shamanic journeying and psychic protection',
      ],
      gaia_resonance:   'SovereignCore + ChthonField + ClarusLens',
      safety_warning:   'Anisotropic hardness — very sharp on soft axis. Handle with care to avoid splinters. Not safe for water due to perfect cleavage and potential delamination. Never for elixirs.',
    },
  },

  // ── 3. Black Moonstone ────────────────────────────────────────────────────────
  {
    name:        'Black Moonstone',
    trade_name:  false,
    mindat_id:   3155,

    physical: {
      id:            3155,
      longid:        'black-moonstone',
      guid:          'b3c4d5e6-f7a8-9012-cdef-123456789012',
      name:          'Black Moonstone',
      ima_formula:   '(Na,K)AlSi₃O₈',
      mindat_formula: '(Na,K)AlSi3O8',
      ima_status:    'A',
      ima_year:      null,
      strunzten:     '9.FA.35',
      dana8ed:       '76.1.3.1',
      crystal_system: 'Monoclinic / Triclinic',
      hardness_min:  6.0,
      hardness_max:  6.5,
      specific_gravity_min: 2.57,
      specific_gravity_max: 2.60,
      cleavage:      'Perfect on {001}, good on {010}',
      fracture:      'Uneven to conchoidal',
      tenacity:      'Brittle',
      luster:        ['Vitreous', 'Pearly (adularescent)'],
      diaphaneity:   ['Translucent', 'Opaque'],
      colour:        'Dark grey to black with silver or blue-white adularescence (schiller)',
      streak:        'White',
      fluorescence:  null,
      ri_min:        1.518,
      ri_max:        1.530,
      birefringence: 0.008,
      optical_type:  'B',
      shortdesc:     'Dark variety of labradorite-series feldspar (from Madagascar) exhibiting blue-silver adularescence. Distinct from classic white moonstone (adularia).',
      updttime:      '2024-12-10T00:00:00Z',
      mindat_url:    'https://www.mindat.org/min-3155.html',
      piezoelectric:    false,
      safe_for_water:   false,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Black Moonstone',
      refractive_index: { n_alpha: 1.518, n_beta: 1.524, n_gamma: 1.530 },
      birefringence:    0.008,
      optical_sign:     '-',
      dispersion:       'Weak',
      pleochroism:      null,
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 400, max: 500 },
      spectra:          [],
    },

    color: {
      primary_color:          'Black with silver adularescence',
      color_variants:         ['Dark grey-black', 'Blue-silver flash', 'Purple-black with shimmer'],
      dominant_wavelength_nm: 460,
      oklch:                  { l: 0.18, c: 0.04, h: 270 },
      hex:                    '#1e1e3a',
      munsell:                '5PB 2/2',
      color_temperature_k:    null,
      psychological_effects:  ['Deep intuition', 'New beginnings', 'Void potential', 'Feminine mystery'],
      harmonics: {
        complementary_hue: 90,
        triadic_hues:      [30, 150],
        analogous_range:   [250, 290],
      },
    },

    color_layer: 'natural',
    yin_yang_pair: 'yin',

    metaphysical: {
      mineral_name:     'Black Moonstone',
      chakra_primary:   'Third Eye',
      chakra_secondary: ['Crown', 'Root'],
      element:          ['Water', 'Aether'],
      planet:           ['Moon', 'Saturn'],
      archetype: ['The New Moon', 'The Void Before Creation', 'The Dark Womb'],
      zodiac:    ['Scorpio', 'Capricorn', 'Cancer'],
      numerology: 1,
      angel_number: '000',
      intention: 'I rest in the fertile dark. The new cycle is already beginning within me.',
      traditions:       ['Crystal healing', 'Moon magic', 'New Moon ceremony', 'Dark goddess traditions'],
      properties:       [
        'Stone of new beginnings and void potential',
        'The darkest phase of the lunar cycle crystallised in mineral form',
        'Deepens intuition and access to the subconscious during new moon phases',
        'Supports endings that make space for what is coming',
        'Protective and deeply feminine; shields sensitive energy fields',
        'Facilitates shadow integration without overwhelm',
      ],
      gaia_resonance:   'SomnusVeil + ClarusLens + ChthonField',
      safety_warning:   'Feldspar — avoid prolonged water exposure due to cleavage; not for elixirs. The silvery flash is from internal lamellar twinning, not surface treatment — safe for compassion stone for shadow work.',
    },
  },

  // ── 4. Black Obsidian ─────────────────────────────────────────────────────────
  {
    name:        'Black Obsidian',
    trade_name:  false,
    mindat_id:   2950,

    physical: {
      id:            2950,
      longid:        'black-obsidian',
      guid:          'c4d5e6f7-a8b9-0123-defa-234567890123',
      name:          'Black Obsidian',
      ima_formula:   'SiO₂ + variable',
      mindat_formula: 'SiO2',
      ima_status:    null,
      ima_year:      null,
      strunzten:     null,
      dana8ed:       null,
      crystal_system: 'Amorphous (volcanic glass)',
      hardness_min:  5.0,
      hardness_max:  5.5,
      specific_gravity_min: 2.35,
      specific_gravity_max: 2.45,
      cleavage:      null,
      fracture:      'Conchoidal (extremely sharp)',
      tenacity:      'Brittle',
      luster:        ['Vitreous'],
      diaphaneity:   ['Translucent (thin edges)', 'Opaque'],
      colour:        'Black, may show golden or silver sheen (inclusions)',
      streak:        'White',
      fluorescence:  null,
      ri_min:        1.480,
      ri_max:        1.510,
      birefringence: null,
      optical_type:  'Isotropic',
      shortdesc:     'Volcanic glass (rhyolitic) — amorphous silica. Razor-sharp conchoidal fracture; used in surgical blades. Natural glass formed by rapid lava cooling.',
      updttime:      '2024-11-05T00:00:00Z',
      mindat_url:    'https://www.mindat.org/min-2950.html',
      piezoelectric:    false,
      safe_for_water:   true,
      safe_for_hardware: false,
    },

    optical: {
      mineral_name:     'Black Obsidian',
      refractive_index: { n: 1.490 },
      birefringence:    null,
      optical_sign:     null,
      dispersion:       'Low',
      pleochroism:      null,
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: null,
      spectra:          [],
    },

    color: {
      primary_color:          'Black',
      color_variants:         ['Golden sheen', 'Silver sheen', 'Rainbow iridescence', 'Mahogany (brown-black)'],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.10, c: 0.01, h: 40 },
      hex:                    '#151515',
      munsell:                'N 1/',
      color_temperature_k:    null,
      psychological_effects:  ['Truth', 'Psychic protection', 'Shadow exposure', 'Grounding'],
      harmonics: {
        complementary_hue: null,
        triadic_hues:      null,
        analogous_range:   null,
      },
    },

    color_layer: 'natural',
    yin_yang_pair: 'yin',

    metaphysical: {
      mineral_name:     'Black Obsidian',
      chakra_primary:   'Root',
      chakra_secondary: ['Earth Star', 'Third Eye'],
      element:          ['Fire', 'Earth'],
      planet:           ['Saturn', 'Pluto'],
      archetype:        ['The Mirror', 'The Truth-Teller', 'The Void'],
      zodiac:           ['Scorpio', 'Sagittarius', 'Capricorn'],
      numerology:       1,
      angel_number:     111,
      intention:        'I face truth without flinching. The mirror of obsidian reveals what must be seen.',
      traditions:       ['Mesoamerican ritual (Aztec/Maya)', 'Shamanic scrying', 'Western crystal healing'],
      properties:       [
        'The ultimate mirror stone — reflects truth of character without softening',
        'Cuts through illusions, deceptions, and self-deception',
        'Rapid and powerful psychic protection; seals the aura',
        'Historically used for scrying, arrow tips, and surgical blades',
        'Supports deep shadow work — recommended for experienced practitioners',
        'Draws out mental stress, tension, and suppressed emotions',
      ],
      gaia_resonance:   'SovereignCore + ChthonField + ClarusLens',
      safety_warning:   'Volcanic glass — edges and fractures are razor-sharp. Handle with care. Safe for water (silica-based). For shadow work: use intentionally; intensity can be overwhelming for beginners.',
    },
  },

  // ── 5. Black Onyx ─────────────────────────────────────────────────────────────
  {
    name:        'Black Onyx',
    trade_name:  false,
    mindat_id:   2998,

    physical: {
      id:            2998,
      longid:        'black-onyx',
      guid:          'd5e6f7a8-b9c0-1234-efab-345678901234',
      name:          'Black Onyx',
      ima_formula:   'SiO₂',
      mindat_formula: 'SiO2',
      ima_status:    'A',
      ima_year:      null,
      strunzten:     '4.DA.05',
      dana8ed:       '75.1.3.1',
      crystal_system: 'Trigonal (cryptocrystalline)',
      hardness_min:  6.5,
      hardness_max:  7.0,
      specific_gravity_min: 2.58,
      specific_gravity_max: 2.64,
      cleavage:      null,
      fracture:      'Conchoidal',
      tenacity:      'Tough',
      luster:        ['Waxy', 'Dull'],
      diaphaneity:   ['Opaque'],
      colour:        'Solid black (usually dyed chalcedony; natural black onyx is rare)',
      streak:        'White',
      fluorescence:  null,
      ri_min:        1.530,
      ri_max:        1.540,
      birefringence: 0.004,
      optical_type:  'U',
      shortdesc:     'Black banded variety of chalcedony. Commercial black onyx is typically dyed grey chalcedony. Natural black onyx (undyed) is significantly rarer.',
      updttime:      '2024-09-14T00:00:00Z',
      mindat_url:    'https://www.mindat.org/min-2998.html',
      piezoelectric:    false,
      safe_for_water:   true,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Black Onyx',
      refractive_index: { n_omega: 1.539, n_epsilon: 1.530 },
      birefringence:    0.004,
      optical_sign:     '-',
      dispersion:       'Weak',
      pleochroism:      null,
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: null,
      spectra:          [],
    },

    color: {
      primary_color:          'Solid black',
      color_variants:         ['Black with white banding (sardonyx)', 'Deep charcoal'],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.08, c: 0.01, h: 0 },
      hex:                    '#111111',
      munsell:                'N 1/',
      color_temperature_k:    null,
      psychological_effects:  ['Strength', 'Stamina', 'Self-control', 'Grounding', 'Resilience'],
      harmonics: {
        complementary_hue: null,
        triadic_hues:      null,
        analogous_range:   null,
      },
    },

    color_layer: 'natural',
    yin_yang_pair: 'yin',

    metaphysical: {
      mineral_name:     'Black Onyx',
      chakra_primary:   'Root',
      chakra_secondary: ['Solar Plexus', 'Earth Star'],
      element:          ['Earth'],
      planet:           ['Saturn', 'Mars'],
      archetype:        ['The Warrior', 'The Steadfast', 'The Enduring'],
      zodiac:           ['Leo', 'Capricorn', 'Scorpio'],
      numerology:       6,
      angel_number:     666,
      intention:        'I stand firm. My strength is rooted and my will is unshakeable.',
      traditions:       ['Roman amulet tradition', 'Arabic talismanic use', 'Western crystal healing'],
      properties:       [
        'Stone of inner strength, stamina, and self-mastery',
        'Absorbs and transforms negative energy in the environment',
        'Supports grief processing and recovery from emotional exhaustion',
        'Historically used for protection in battle and argument',
        'Anchors scattered energy — helpful for focus and discipline',
        'Often used in grief jewellery as a stone of endurance',
      ],
      gaia_resonance:   'SovereignCore + ChthonField',
      safety_warning:   'Commercial black onyx is almost universally dyed. The dye (iron sulfate or sugar-acid process) is stable and non-toxic under normal use. Safe for water. Avoid prolonged boiling or harsh chemicals which may strip the dye.',
    },
  },

];

export default BATCH_B3;
