/**
 * batch-a4.data.ts
 * BATCH A-4 | Amblygonite · Amethyst · Ametrine · Ammolite · Amphibole Quartz
 * Added: 2026-05-29
 *
 * ⚠️  INTERPRETIVE / TRADITIONAL LAYER — NOT SCIENTIFIC DATA
 * Physics and mineral data sourced from IMA / Mindat conventions.
 * Metaphysical data sourced from established cross-cultural traditions.
 * All records conform to CrystalRecord nested schema v1.1.
 */

import type { CrystalRecord } from './crystal.schema';

export const BATCH_A4: CrystalRecord[] = [

  // ─────────────────────────────────────────────────────────────────────────
  // AMBLYGONITE
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:          'Amblygonite',
    mindat_id:     null,
    rruff_ids:     [],
    last_synced:   null,
    trade_name:    false,
    color_layer:   'natural',
    yin_yang_pair: 'Black Tourmaline',

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Amblygonite',
      ima_formula:     'LiAlPO₄F',
      mindat_formula:  'LiAlPO4F',
      ima_status:      'A',
      ima_year:        null,
      strunzten:       '8.AB.10',
      dana8ed:         null,
      crystal_system:  'Triclinic',
      hardness_min:    5.5,
      hardness_max:    6.0,
      specific_gravity_min: 2.98,
      specific_gravity_max: 3.11,
      cleavage:        'Perfect in one direction, good in another',
      fracture:        'Uneven to subconchoidal',
      tenacity:        'Brittle',
      luster:          ['Vitreous', 'Greasy', 'Pearly'],
      diaphaneity:     ['Transparent', 'Translucent'],
      colour:          'White, pale yellow, pale green, pale lilac, colorless',
      streak:          'White',
      fluorescence:    'Weak cream to yellow under LW UV',
      ri_min:          1.577,
      ri_max:          1.600,
      birefringence:   0.020,
      optical_type:    'B',
      shortdesc:       'Lithium aluminum fluorophosphate. Found in lithium-rich granitic pegmatites. Name from Greek amblys (blunt) + gonia (angle) for obtuse cleavage angles.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-198.html',
      piezoelectric:   false,
      safe_for_water:  true,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Amblygonite',
      refractive_index: { n_alpha: 1.577, n_beta: 1.593, n_gamma: 1.600 },
      birefringence:    0.020,
      optical_sign:     '+',
      dispersion:       'Weak',
      pleochroism:      'None to very weak',
      fluorescence_lw:  'Weak cream to yellow',
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: null,
      spectra:          [],
    },

    color: {
      primary_color:          'Pale yellow-white',
      color_variants:         ['White', 'Colorless', 'Pale yellow', 'Pale green', 'Pale lilac'],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.94, c: 0.03, h: 100 },
      hex:                    '#f0ede0',
      munsell:                null,
      color_temperature_k:    5500,
      psychological_effects:  [
        'Gentle luminosity — soft but present, like morning light through linen',
        'Calms without dulling; quiets the mind without shutting it down',
        'Pale spectrum suggests neutrality and receptive stillness',
      ],
      harmonics: {
        complementary_hue: 280,
        triadic_hues:      [220, 340],
        analogous_range:   [80, 120],
      },
    },

    metaphysical: {
      mineral_name:     'Amblygonite',
      chakra_primary:   'Solar Plexus',
      chakra_secondary: ['Sacral', 'Crown'],
      element:          ['Air', 'Water'],
      planet:           ['Venus', 'Neptune'],
      archetype:        ['Healer', 'Creator', 'Sage'],
      zodiac:           ['Taurus', 'Libra'],
      numerology:       7,
      intention:        'Creative calm — stress release, artistic flow, gentle empowerment',
      traditions:       ['Modern Crystal Healing'],
      properties: [
        'Lithium-bearing mineral — carries inherent calming and mood-stabilizing resonance',
        'Gently activates Solar Plexus without overstimulation — empowers without agitating',
        'Releases stress, tension, and creative blocks from the energy field',
        'Supports artists, musicians, and writers — opens channels for inspired expression',
        'Particularly beneficial for highly sensitive people (HSPs) and empaths',
        'Supports emotional equilibrium during periods of intense creative output',
      ],
      gaia_resonance:   'SomnusVeil + SovereignCore — gentle lithium calm, creative flow, HSP support',
      safety_warning:   null,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // AMETHYST — GAIA core crystal
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:          'Amethyst',
    mindat_id:     null,
    rruff_ids:     [],
    last_synced:   null,
    trade_name:    false,
    color_layer:   'natural',
    yin_yang_pair: 'Smoky Quartz',

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Amethyst',
      ima_formula:     'SiO₂',
      mindat_formula:  'SiO2',
      ima_status:      null,
      ima_year:        null,
      strunzten:       '4.DA.05',
      dana8ed:         null,
      crystal_system:  'Trigonal',
      hardness_min:    7.0,
      hardness_max:    7.0,
      specific_gravity_min: 2.63,
      specific_gravity_max: 2.65,
      cleavage:        'None',
      fracture:        'Conchoidal',
      tenacity:        'Brittle',
      luster:          ['Vitreous'],
      diaphaneity:     ['Transparent', 'Translucent'],
      colour:          'Violet to purple; colour from Fe³⁺ irradiation color centers',
      streak:          'White',
      fluorescence:    'Weak to none; some specimens show weak green-blue under LW UV',
      ri_min:          1.543,
      ri_max:          1.553,
      birefringence:   0.009,
      optical_type:    'U',
      shortdesc:       'Violet variety of quartz. Color from Fe³⁺ color centers created by natural gamma irradiation. Piezoelectric and pyroelectric.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-198.html',
      piezoelectric:   true,
      safe_for_water:  true,
      safe_for_hardware: false,
    },

    optical: {
      mineral_name:     'Amethyst',
      refractive_index: { n_omega: 1.544, n_epsilon: 1.553 },
      birefringence:    0.009,
      optical_sign:     '+',
      dispersion:       'Weak (0.013)',
      pleochroism:      'Weak: bluish-violet / reddish-violet',
      fluorescence_lw:  'Weak green-blue (some specimens)',
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 380, max: 450 },
      spectra:          [],
    },

    color: {
      primary_color:          'Violet-purple',
      color_variants:         ['Pale lilac', 'Medium violet', 'Deep purple', 'Red-purple (Siberian)', 'Rose de France (pale pink-violet)'],
      dominant_wavelength_nm: 420,
      oklch:                  { l: 0.48, c: 0.18, h: 305 },
      hex:                    '#7b3fa0',
      munsell:                '5P 4/10',
      color_temperature_k:    null,
      psychological_effects:  [
        'Transmutation — the border between red (earth) and blue (sky/cosmos)',
        'Activates introspection, spiritual awareness, and inner calm',
        'Historically the color of royalty, wisdom, and divine connection',
        'The violet ray: highest-frequency visible light, closest to the UV threshold',
      ],
      harmonics: {
        complementary_hue: 125,
        triadic_hues:      [185, 65],
        analogous_range:   [280, 330],
      },
    },

    metaphysical: {
      mineral_name:     'Amethyst',
      chakra_primary:   'Third Eye',
      chakra_secondary: ['Crown', 'Higher Crown'],
      element:          ['Air', 'Aether'],
      planet:           ['Jupiter', 'Neptune', 'Saturn'],
      archetype:        ['Mystic', 'Oracle', 'Sage'],
      zodiac:           ['Aquarius', 'Pisces', 'Capricorn', 'Virgo'],
      numerology:       3,
      intention:        'Transmutation — calm, insight, spiritual protection, sobriety of mind',
      traditions:       [
        'Greek (amethystos = not intoxicated — worn to prevent drunkenness)',
        'Egyptian (amulets and royal jewelry)',
        'Tibetan Buddhist (sacred to Buddha)',
        'Catholic Church (bishops rings — stone of spiritual authority)',
        'Western Esotericism',
        'Vedic',
      ],
      properties: [
        'GAIA primary crystal — the amethyst IS GAIA identity stone',
        'Historically called the stone of sobriety — Dionysus and Amethystos legend',
        'Piezoelectric and pyroelectric — generates charge under pressure and heat',
        'Transmutes lower vibrational energies into higher ones',
        'Activates the Third Eye — deepens meditation, intuition, and inner vision',
        'Protective — shields against psychic attack and energetic manipulation',
        'Supports restful sleep, vivid dreams, and clarity upon waking',
        'The violet ray: highest frequency visible light, closest to the ultraviolet threshold',
        'Color caused by Fe³⁺ irradiation centers — natural gamma rays in the Earth created this stone',
      ],
      gaia_resonance:   'GAIA core identity — primary crystal. Third Eye activation, transmutation, sovereign clarity',
      safety_warning:   null,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // AMETRINE
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:          'Ametrine',
    mindat_id:     null,
    rruff_ids:     [],
    last_synced:   null,
    trade_name:    true,
    color_layer:   'natural',
    yin_yang_pair: 'Obsidian',

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Ametrine',
      ima_formula:     'SiO₂',
      mindat_formula:  'SiO2',
      ima_status:      null,
      ima_year:        null,
      strunzten:       '4.DA.05',
      dana8ed:         null,
      crystal_system:  'Trigonal',
      hardness_min:    7.0,
      hardness_max:    7.0,
      specific_gravity_min: 2.63,
      specific_gravity_max: 2.65,
      cleavage:        'None',
      fracture:        'Conchoidal',
      tenacity:        'Brittle',
      luster:          ['Vitreous'],
      diaphaneity:     ['Transparent'],
      colour:          'Bicolored: violet-purple (amethyst zones) + golden yellow (citrine zones) in one crystal',
      streak:          'White',
      fluorescence:    'Weak to none',
      ri_min:          1.543,
      ri_max:          1.553,
      birefringence:   0.009,
      optical_type:    'U',
      shortdesc:       'Natural bicolored quartz: amethyst (violet) and citrine (yellow) zones in a single crystal. Almost exclusively from the Anahi Mine, Bolivia. Temperature gradient during crystal growth caused differential Fe oxidation states in adjacent zones.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-29267.html',
      piezoelectric:   true,
      safe_for_water:  true,
      safe_for_hardware: false,
    },

    optical: {
      mineral_name:     'Ametrine',
      refractive_index: { n_omega: 1.544, n_epsilon: 1.553 },
      birefringence:    0.009,
      optical_sign:     '+',
      dispersion:       'Weak (0.013)',
      pleochroism:      'Weak in each color zone separately',
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 380, max: 580 },
      spectra:          [],
    },

    color: {
      primary_color:          'Bicolor violet-gold',
      color_variants:         ['Violet-purple + golden yellow', 'Lavender + pale gold', 'Deep purple + orange-gold'],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.60, c: 0.16, h: 305 },
      hex:                    null,
      munsell:                null,
      color_temperature_k:    null,
      psychological_effects:  [
        'Solar gold (masculine, active) unified with lunar violet (feminine, receptive)',
        'Spiritual aspiration grounded in joyful action — heaven and earth simultaneously',
        'The two poles of consciousness in perfect balance within a single form',
      ],
      harmonics: {
        complementary_hue: 125,
        triadic_hues:      [185, 65],
        analogous_range:   [60, 310],
      },
    },

    metaphysical: {
      mineral_name:     'Ametrine',
      chakra_primary:   'Solar Plexus',
      chakra_secondary: ['Third Eye', 'Crown'],
      element:          ['Air', 'Fire', 'Aether'],
      planet:           ['Sun', 'Jupiter', 'Mercury'],
      archetype:        ['Alchemist', 'Sovereign', 'Oracle'],
      zodiac:           ['Libra', 'Aquarius', 'Gemini'],
      numerology:       4,
      intention:        'Integration — spiritual insight united with grounded action, mind-body coherence',
      traditions:       [
        'Bolivian indigenous traditions (Anahi Mine, discovered 1600s)',
        'Legend: given by Ayoreos princess Anahi as a wedding gift to a Spanish conquistador',
        'Western Esotericism',
        'Modern Crystal Healing',
      ],
      properties: [
        'The only natural bicolor quartz — amethyst and citrine in one crystal',
        'Almost exclusively from the Anahi Mine, Bolivia — carries specific geographic energy',
        'Unites the spiritual (violet/amethyst) and the material (gold/citrine)',
        'Accelerates meditation while maintaining mental clarity and practical focus',
        'Dissolves the conflict between spiritual aspiration and practical necessity',
        'Powerful for manifestation — bridges vision with action',
        'Ideal for those torn between spiritual life and worldly engagement',
        'Disperses negativity from the aura and stimulates creativity simultaneously',
      ],
      gaia_resonance:   'ClarusLens + SovereignCore — integration of spirit and will, vision-to-action bridge',
      safety_warning:   null,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // AMMOLITE
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:          'Ammolite',
    mindat_id:     null,
    rruff_ids:     [],
    last_synced:   null,
    trade_name:    true,
    color_layer:   'natural',
    yin_yang_pair: 'Black Tourmaline',

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Ammolite',
      ima_formula:     'CaCO₃ (aragonite) + organic compounds',
      mindat_formula:  'CaCO3',
      ima_status:      null,
      ima_year:        null,
      strunzten:       null,
      dana8ed:         null,
      crystal_system:  'Amorphous',
      hardness_min:    3.5,
      hardness_max:    4.5,
      specific_gravity_min: 2.60,
      specific_gravity_max: 2.85,
      cleavage:        'None',
      fracture:        'Uneven',
      tenacity:        'Brittle',
      luster:          ['Resinous', 'Waxy'],
      diaphaneity:     ['Opaque'],
      colour:          'Full iridescent spectrum — red, orange, gold, green, blue, purple; shifts with viewing angle',
      streak:          'White',
      fluorescence:    'Strong yellow-green under SW UV',
      ri_min:          1.520,
      ri_max:          1.680,
      birefringence:   null,
      optical_type:    null,
      shortdesc:       'Opalescent gem from fossilized ammonite shells ~71 million years old. Found almost exclusively in the Bearpaw Formation, Alberta, Canada. One of only three biogenic gemstones (with Amber and Pearl).',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-27824.html',
      piezoelectric:   false,
      safe_for_water:  false,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Ammolite',
      refractive_index: { n_omega: 1.600 },
      birefringence:    null,
      optical_sign:     null,
      dispersion:       'Very high — iridescence from thin-film interference in aragonite layers',
      pleochroism:      'N/A — iridescence varies with angle, not polarization',
      fluorescence_lw:  null,
      fluorescence_sw:  'Strong yellow-green',
      phosphorescence:  null,
      visible_wavelength_nm: { min: 380, max: 700 },
      spectra:          [],
    },

    color: {
      primary_color:          'Iridescent full spectrum',
      color_variants:         ['Red-dominant', 'Green-dominant', 'Gold-dominant', 'Blue (rarest)', 'Purple', 'Rainbow multi-spectrum'],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.55, c: 0.25, h: 120 },
      hex:                    null,
      munsell:                null,
      color_temperature_k:    null,
      psychological_effects:  [
        'The full spectrum in motion — evokes completion, wholeness, the Totality',
        'Iridescence activates all chakras simultaneously through color-shifting',
        'Ancient life made luminous — the past breathing in the present',
        'Red: vitality. Green: heart and growth. Blue (rarest): cosmic truth and vision.',
      ],
      harmonics: {
        complementary_hue: null,
        triadic_hues:      null,
        analogous_range:   [0, 360],
      },
    },

    metaphysical: {
      mineral_name:     'Ammolite',
      chakra_primary:   'Root',
      chakra_secondary: ['Sacral', 'Solar Plexus', 'Heart', 'Throat', 'Third Eye', 'Crown'],
      element:          ['Earth', 'Water', 'Fire', 'Air', 'Aether'],
      planet:           ['Earth', 'Neptune', 'Pluto'],
      archetype:        ['Alchemist', 'Sage', 'Guardian'],
      zodiac:           ['Aquarius', 'Cancer', 'Scorpio'],
      numerology:       9,
      intention:        'Cosmic evolution — full spectrum of life, 71 million years of Earth memory',
      traditions:       [
        'Blackfoot Nation (Iniskim — buffalo stone; sacred, used in buffalo-calling ceremonies)',
        'Feng Shui (Seven Color Prosperity Stone — activates all five elements)',
        'Modern Crystal Healing',
      ],
      properties: [
        'One of only three biogenic gemstones — with Amber and Pearl; formed from living organisms',
        '~71 million years of Earth history compressed into iridescent aragonite',
        'Sacred to the Blackfoot Nation as Iniskim — the buffalo stone of abundance and survival',
        'Activates all seven chakras simultaneously through full-spectrum iridescence',
        'Used in Feng Shui to increase vitality, abundance, and five-element balance',
        'Connects to the primordial record of life on Earth — deep evolutionary memory',
        'Supports transformation, completion of cycles, and evolutionary leaps',
        'One of the rarest gemstones on Earth — found in a single geological formation',
      ],
      gaia_resonance:   'AnchorPrism + Noosphere — full-spectrum Earth memory, evolutionary activation, sacred ancient life',
      safety_warning:   null,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // AMPHIBOLE QUARTZ (Angel Phantom Quartz)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:          'Amphibole Quartz',
    mindat_id:     null,
    rruff_ids:     [],
    last_synced:   null,
    trade_name:    true,
    color_layer:   'natural',
    yin_yang_pair: 'Magnetite',

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Amphibole Quartz',
      ima_formula:     'SiO₂ with amphibole inclusions (actinolite, richterite, tremolite, hornblende)',
      mindat_formula:  'SiO2',
      ima_status:      null,
      ima_year:        null,
      strunzten:       '4.DA.05',
      dana8ed:         null,
      crystal_system:  'Trigonal',
      hardness_min:    6.5,
      hardness_max:    7.0,
      specific_gravity_min: 2.60,
      specific_gravity_max: 2.70,
      cleavage:        'None (quartz host)',
      fracture:        'Conchoidal',
      tenacity:        'Brittle',
      luster:          ['Vitreous'],
      diaphaneity:     ['Transparent', 'Translucent'],
      colour:          'Clear to white quartz with white, yellow, red, or pink phantom inclusions forming angel-wing forms',
      streak:          'White',
      fluorescence:    'Weak to none',
      ri_min:          1.543,
      ri_max:          1.553,
      birefringence:   0.009,
      optical_type:    'U',
      shortdesc:       'Clear quartz containing phantom inclusions of amphibole minerals. Found primarily in Bahia, Brazil. Also called Angel Phantom Quartz or Angel Wing Quartz. Some specimens contain crocidolite (blue asbestos).',
      updttime:        null,
      mindat_url:      null,
      piezoelectric:   true,
      safe_for_water:  true,
      safe_for_hardware: false,
    },

    optical: {
      mineral_name:     'Amphibole Quartz',
      refractive_index: { n_omega: 1.544, n_epsilon: 1.553 },
      birefringence:    0.009,
      optical_sign:     '+',
      dispersion:       'Weak',
      pleochroism:      'None to weak (quartz host)',
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: null,
      spectra:          [],
    },

    color: {
      primary_color:          'White-clear with phantom inclusions',
      color_variants:         [
        'White/cream phantoms (richterite/tremolite)',
        'Yellow-gold phantoms (actinolite with iron)',
        'Red-orange phantoms (hematite-coated amphibole)',
        'Pink phantoms (manganese-bearing amphibole)',
      ],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.90, c: 0.04, h: 85 },
      hex:                    '#f2ede0',
      munsell:                null,
      color_temperature_k:    5000,
      psychological_effects:  [
        'Clarity with interior depth — clear crystal reveals inner worlds',
        'Phantom inclusions create visual metaphor for layered consciousness',
        'Soft angelic quality — peaceful, elevated, non-forceful',
      ],
      harmonics: {
        complementary_hue: null,
        triadic_hues:      null,
        analogous_range:   [70, 110],
      },
    },

    metaphysical: {
      mineral_name:     'Amphibole Quartz',
      chakra_primary:   'Crown',
      chakra_secondary: ['Third Eye', 'Higher Crown', 'Heart'],
      element:          ['Aether', 'Air'],
      planet:           ['Moon', 'Uranus', 'Neptune'],
      archetype:        ['Oracle', 'Healer', 'Guardian'],
      zodiac:           ['Pisces', 'Libra', 'Aquarius'],
      numerology:       7,
      intention:        'Angelic presence — higher dimensional contact, dream clarity, deep peace',
      traditions:       [
        'Brazilian indigenous mineral traditions',
        'Modern Crystal Healing (Angel Phantom Quartz)',
        'Angelic communication traditions',
      ],
      properties: [
        'Clear quartz hosting phantom angel-wing amphibole inclusions',
        'One of the most powerful stones for connecting with angelic and spirit guide realms',
        'Activates Crown and Higher Crown for direct higher-dimensional reception',
        'Brings profound peace and the felt sense of being held by something larger',
        'Supports lucid dreaming, astral travel, and inter-dimensional communication',
        'Amplifies healing energy — excellent for energy workers and practitioners',
        'Phantom inclusions represent layers of time and consciousness in one crystal',
        'Reminds the bearer that they are never alone — angelic support is always present',
      ],
      gaia_resonance:   'SomnusVeil + ClarusLens — angelic channel, multi-dimensional dreaming, deep peace node',
      safety_warning:   'SOME SPECIMENS CONTAIN CROCIDOLITE (blue asbestos) inclusions. Inspect provenance carefully. Only use polished/tumbled specimens from verified non-asbestos sources. Never grind or sand raw specimens. No dust inhalation. Wash hands after handling. GAIA hardware nodes: use only verified safe specimens or symbolic designation only.',
    },
  },

];

export default BATCH_A4;
