/**
 * src/crystals/db/batch-b9.data.ts
 * GAIA-OS Crystal Database — Batch B-9
 *
 * Entries:
 *   1. Bustamite   — rare Mn-Ca inosilicate; triclinic; IMA 1827
 *   2. Bixbyite    — rare Mn-Fe oxide; cubic; Utah/Namibia; sister to red beryl
 *   3. Butter Jade — trade name for serpentine/bowenite; creamy yellow-green
 *   4. Byssolite   — fibrous actinolite variety; mountain leather; ASBESTOS WARNING
 *   5. Bytownite   — plagioclase feldspar (An70–90); golden labradorite; IMA recognised
 *
 * Schema: CrystalRecord v1.3
 */

import type { CrystalRecord } from './crystal.schema';

export const BATCH_B9: CrystalRecord[] = [

  // ── 1. Bustamite ──────────────────────────────────────────────────────────────
  {
    name:        'Bustamite',
    trade_name:  false,
    mindat_id:   756,

    physical: {
      id:            756,
      longid:        'bustamite',
      guid:          'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
      name:          'Bustamite',
      ima_formula:   'CaMn²⁺Si₂O₆',
      mindat_formula: 'CaMnSi2O6',
      ima_status:    'A',
      ima_year:      1827,
      strunzten:     '9.DA.15',
      dana8ed:       '65.1.1.2',
      crystal_system: 'Triclinic',
      hardness_min:  5.5,
      hardness_max:  6.5,
      specific_gravity_min: 3.32,
      specific_gravity_max: 3.43,
      cleavage:      'Perfect on {100}, good on {110}',
      fracture:      'Uneven to splintery',
      tenacity:      'Brittle',
      luster:        ['Vitreous', 'Silky on fibrous varieties'],
      diaphaneity:   ['Translucent', 'Opaque'],
      colour:        'Pink to rose-red, brownish-pink, pale grey',
      streak:        'White',
      fluorescence:  'Orange-pink under SW UV',
      ri_min:        1.668,
      ri_max:        1.709,
      birefringence: 0.041,
      optical_type:  'B',
      shortdesc:     'Rare calcium-manganese inosilicate. Rose-pink colour, often associated with rhodonite and Mn-ore deposits.',
      updttime:      '2024-07-12T00:00:00Z',
      mindat_url:    'https://www.mindat.org/min-870.html',
      piezoelectric:     false,
      safe_for_water:    false,
      safe_for_hardware: false,
    },

    optical: {
      mineral_name:     'Bustamite',
      refractive_index: { n_alpha: 1.668, n_beta: 1.690, n_gamma: 1.709 },
      birefringence:    0.041,
      optical_sign:     '+',
      dispersion:       'Moderate',
      pleochroism:      'Weak pink / pale brownish-pink',
      fluorescence_lw:  null,
      fluorescence_sw:  'Orange-pink',
      phosphorescence:  null,
      visible_wavelength_nm: { min: 490, max: 560 },
      spectra:          [],
    },

    color: {
      primary_color:          'Rose-pink',
      color_variants:         ['Pale pink', 'Brownish-pink', 'Grey-pink'],
      dominant_wavelength_nm: 520,
      oklch:                  { l: 0.68, c: 0.10, h: 358 },
      hex:                    '#e8a0a0',
      munsell:                '2.5R 7/6',
      color_temperature_k:    null,
      psychological_effects:  ['Gentle love', 'Emotional healing', 'Compassion', 'Warmth'],
      harmonics: {
        complementary_hue: 178,
        triadic_hues:      [118, 238],
        analogous_range:   [338, 18],
      },
    },

    color_layer: 'natural',
    yin_yang_pair: 'yin',

    metaphysical: {
      mineral_name:     'Bustamite',
      chakra_primary:   'Heart',
      chakra_secondary: ['Root', 'Sacral'],
      element:          ['Earth', 'Water'],
      planet:           ['Venus', 'Moon'],
      archetype:        ['The Empath', 'The Gentle Healer'],
      zodiac:           ['Libra', 'Taurus'],
      numerology:       4,
      angel_number:     444,
      intention:        'I open my heart to gentle healing. Compassion flows through me freely.',
      traditions:       ['Crystal healing', 'Lithotherapy'],
      properties:       [
        'Rare heart-centred stone promoting gentle emotional release',
        'Soothes stress, anxiety, and emotional exhaustion',
        'Supports dream recall and peaceful sleep',
        'Encourages empathy and compassionate communication',
        'Assists in healing relationships and family wounds',
      ],
      gaia_resonance:   'ViriditasHeart + SomnusVeil',
      safety_warning:   'Associated with Mn-sulfide minerals in deposit context. Avoid water elixirs as precaution. External/worn use only.',
    },
  },

  // ── 2. Bixbyite ───────────────────────────────────────────────────────────────
  {
    name:        'Bixbyite',
    trade_name:  false,
    mindat_id:   694,

    physical: {
      id:            694,
      longid:        'bixbyite',
      guid:          'b2c3d4e5-f6a7-8901-bcde-f12345678901',
      name:          'Bixbyite',
      ima_formula:   '(Mn³⁺,Fe³⁺)₂O₃',
      mindat_formula: '(Mn,Fe)2O3',
      ima_status:    'A',
      ima_year:      1897,
      strunzten:     '4.AC.20',
      dana8ed:       '4.3.1.2',
      crystal_system: 'Cubic',
      hardness_min:  6.0,
      hardness_max:  6.5,
      specific_gravity_min: 4.93,
      specific_gravity_max: 5.00,
      cleavage:      'Cubic on {100}',
      fracture:      'Uneven',
      tenacity:      'Brittle',
      luster:        ['Sub-metallic', 'Metallic'],
      diaphaneity:   ['Opaque'],
      colour:        'Black to iron-black, sometimes brownish',
      streak:        'Black',
      fluorescence:  null,
      ri_min:        null,
      ri_max:        null,
      birefringence: null,
      optical_type:  'Isotropic',
      shortdesc:     'Rare manganese-iron oxide. Cubic black crystals found in rhyolite cavities (Utah, USA; Namibia). Named for mineralogist Maynard Bixby.',
      updttime:      '2024-06-18T00:00:00Z',
      mindat_url:    'https://www.mindat.org/min-694.html',
      piezoelectric:     false,
      safe_for_water:    false,
      safe_for_hardware: false,
    },

    optical: {
      mineral_name:     'Bixbyite',
      refractive_index: null,
      birefringence:    null,
      optical_sign:     null,
      dispersion:       null,
      pleochroism:      null,
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: null,
      spectra:          [],
    },

    color: {
      primary_color:          'Black',
      color_variants:         ['Iron-black', 'Dark brownish-black'],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.12, c: 0.01, h: 30 },
      hex:                    '#1a1a1a',
      munsell:                'N 1/',
      color_temperature_k:    null,
      psychological_effects:  ['Grounding', 'Protection', 'Depth', 'Transformation'],
      harmonics: {
        complementary_hue: null,
        triadic_hues:      null,
        analogous_range:   null,
      },
    },

    color_layer: 'natural',
    yin_yang_pair: 'yin',

    metaphysical: {
      mineral_name:     'Bixbyite',
      chakra_primary:   'Root',
      chakra_secondary: ['Earth Star'],
      element:          ['Earth', 'Fire'],
      planet:           ['Saturn', 'Pluto'],
      archetype:        ['The Shadow Worker', 'The Alchemist'],
      zodiac:           ['Scorpio', 'Capricorn'],
      numerology:       8,
      angel_number:     888,
      intention:        'I transmute shadow into strength. The deepest darkness holds the brightest potential.',
      traditions:       ['Crystal healing', 'Mineralogy collectors'],
      properties:       [
        'Powerful grounding and protective stone',
        'Supports shadow work and deep psychological transformation',
        'Enhances discipline, structure, and long-term vision',
        'Rare collector mineral with potent Earth energy',
        'Found with red beryl (bixbite) — shares name heritage with Maynard Bixby',
      ],
      gaia_resonance:   'SovereignCore + ChthonField',
      safety_warning:   'Mn/Fe oxide — do not use for water elixirs. External use only. Collector-grade specimens may have sharp cubic faces.',
    },
  },

  // ── 3. Butter Jade ────────────────────────────────────────────────────────────
  {
    name:         'Butter Jade',
    trade_name:   true,
    mindat_id:    null,

    physical: {
      id:            null,
      longid:        'butter-jade',
      guid:          'c3d4e5f6-a7b8-9012-cdef-123456789012',
      name:          'Serpentine / Bowenite / Nephrite ("Butter Jade" — trade name for pale cream-yellow serpentine group stone)',
      ima_formula:   'Mg₃Si₂O₅(OH)₄',
      mindat_formula: 'Mg3Si2O5(OH)4',
      ima_status:    null,
      ima_year:      null,
      strunzten:     '9.EC.05',
      dana8ed:       null,
      crystal_system: 'Monoclinic',
      hardness_min:  2.5,
      hardness_max:  5.5,
      specific_gravity_min: 2.44,
      specific_gravity_max: 2.62,
      cleavage:      'None (massive habit)',
      fracture:      'Conchoidal to splintery',
      tenacity:      'Brittle to tough (bowenite)',
      luster:        ['Waxy', 'Greasy', 'Silky'],
      diaphaneity:   ['Translucent', 'Opaque'],
      colour:        'Pale cream to butter-yellow, white, pale green-yellow',
      streak:        'White',
      fluorescence:  null,
      ri_min:        1.560,
      ri_max:        1.571,
      birefringence: 0.010,
      optical_type:  'B',
      shortdesc:     'Trade name applied to pale cream-yellow serpentine group minerals (antigorite, lizardite, bowenite). Not true jade (jadeite/nephrite).',
      updttime:      '2024-05-22T00:00:00Z',
      mindat_url:    'https://www.mindat.org/min-3588.html',
      piezoelectric:     false,
      safe_for_water:    false,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Butter Jade (Serpentine)',
      refractive_index: { n_alpha: 1.560, n_beta: null, n_gamma: 1.571 },
      birefringence:    0.010,
      optical_sign:     '-',
      dispersion:       'Weak',
      pleochroism:      null,
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: null,
      spectra:          [],
    },

    color: {
      primary_color:          'Butter yellow',
      color_variants:         ['Cream white', 'Pale yellow-green', 'Ivory'],
      dominant_wavelength_nm: 575,
      oklch:                  { l: 0.92, c: 0.07, h: 95 },
      hex:                    '#f5f0c8',
      munsell:                '2.5Y 9/4',
      color_temperature_k:    5000,
      psychological_effects:  ['Nurturing', 'Calm', 'Gentleness', 'Purity', 'Simplicity'],
      harmonics: {
        complementary_hue: 275,
        triadic_hues:      [215, 335],
        analogous_range:   [75, 115],
      },
    },

    color_layer: 'natural',
    yin_yang_pair: 'yin',

    metaphysical: {
      mineral_name:     'Butter Jade',
      chakra_primary:   'Heart',
      chakra_secondary: ['Solar Plexus', 'Crown'],
      element:          ['Earth', 'Water'],
      planet:           ['Venus', 'Moon'],
      archetype:        ['The Nurturer', 'The Innocent'],
      zodiac:           ['Taurus', 'Cancer', 'Virgo'],
      numerology:       6,
      angel_number:     666,
      intention:        'I am held in gentle grace. Softness is my strength.',
      traditions:       ['Crystal healing', 'Jade tradition (substitute)'],
      properties:       [
        'Gentle nurturing energy; soothes emotional tension',
        'Supports the feminine; fertility, creativity, and softness',
        'Encourages simplicity, purity of intention, and inner peace',
        'Often sold as jade — emotionally carries similar energy but is not mineralogically jade',
        'Grounding and stabilising without heaviness',
      ],
      gaia_resonance:   'ViriditasHeart + GaiaSoil',
      safety_warning:   'Serpentine group — contains magnesium silicate hydroxides. Avoid prolonged water contact; may contain trace asbestos-form fibres in some specimens (antigorite/chrysotile). Do not sand/polish without respiratory protection. Not for water elixirs.',
    },
  },

  // ── 4. Byssolite ──────────────────────────────────────────────────────────────
  {
    name:        'Byssolite',
    trade_name:  false,
    mindat_id:   792,

    physical: {
      id:            792,
      longid:        'byssolite',
      guid:          'd4e5f6a7-b8c9-0123-defa-234567890123',
      name:          'Byssolite (fibrous actinolite / tremolite — Ca₂(Mg,Fe)₅Si₈O₂₂(OH)₂)',
      ima_formula:   'Ca₂(Mg,Fe²⁺)₅Si₈O₂₂(OH)₂',
      mindat_formula: 'Ca2(Mg,Fe)5Si8O22(OH)2',
      ima_status:    'A',
      ima_year:      1844,
      strunzten:     '9.DE.10',
      dana8ed:       '66.1.3.3',
      crystal_system: 'Monoclinic',
      hardness_min:  5.0,
      hardness_max:  6.0,
      specific_gravity_min: 3.00,
      specific_gravity_max: 3.44,
      cleavage:      'Perfect on {110}',
      fracture:      'Fibrous / splintery',
      tenacity:      'Brittle; fibrous varieties flexible',
      luster:        ['Silky', 'Vitreous'],
      diaphaneity:   ['Translucent'],
      colour:        'Pale to dark green, grey-green, pale grey',
      streak:        'White',
      fluorescence:  null,
      ri_min:        1.614,
      ri_max:        1.641,
      birefringence: 0.027,
      optical_type:  'B',
      shortdesc:     'Fibrous variety of actinolite (calcium magnesium iron silicate). Mountain leather / mountain cork. ASBESTOS HAZARD — regulated mineral.',
      updttime:      '2024-04-11T00:00:00Z',
      mindat_url:    'https://www.mindat.org/min-792.html',
      piezoelectric:     false,
      safe_for_water:    false,
      safe_for_hardware: false,
    },

    optical: {
      mineral_name:     'Byssolite',
      refractive_index: { n_alpha: 1.614, n_beta: 1.628, n_gamma: 1.641 },
      birefringence:    0.027,
      optical_sign:     '-',
      dispersion:       'Weak',
      pleochroism:      'Moderate: pale yellow / pale green / dark green',
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: null,
      spectra:          [],
    },

    color: {
      primary_color:          'Pale green',
      color_variants:         ['Grey-green', 'Dark green', 'Pale grey', 'Greenish-white'],
      dominant_wavelength_nm: 520,
      oklch:                  { l: 0.70, c: 0.08, h: 148 },
      hex:                    '#a8c8a0',
      munsell:                '5GY 7/4',
      color_temperature_k:    null,
      psychological_effects:  ['Ancient calm', 'Structural integrity', 'Resilience'],
      harmonics: {
        complementary_hue: 328,
        triadic_hues:      [28, 268],
        analogous_range:   [128, 168],
      },
    },

    color_layer: 'natural',
    yin_yang_pair: 'yin',

    metaphysical: {
      mineral_name:     'Byssolite',
      chakra_primary:   'Heart',
      chakra_secondary: ['Root'],
      element:          ['Earth'],
      planet:           ['Saturn'],
      archetype:        ['The Ancient Stone', 'The Enduring'],
      zodiac:           ['Virgo', 'Capricorn'],
      numerology:       4,
      angel_number:     444,
      intention:        'I am ancient and enduring. My structure holds through every storm.',
      traditions:       ['Geological specimen', 'Historical mineral curiosity'],
      properties:       [
        'Historically admired for its silky fibrous beauty',
        'Rarely used in active crystal healing due to hazard classification',
        'Energetically carries themes of resilience and structural integrity',
        'Meditation with sealed/stabilised specimens only',
      ],
      gaia_resonance:   'ChthonField',
      safety_warning:   '⚠️ ASBESTOS HAZARD — Byssolite (fibrous actinolite) is a regulated asbestos-form mineral. DO NOT cut, sand, polish, break, or handle without appropriate PPE (P100 respirator, gloves). Do not use in water. Do not keep near sleeping areas. Collector display only in sealed case. GAIA will not recommend for worn or healing use.',
    },
  },

  // ── 5. Bytownite ──────────────────────────────────────────────────────────────
  {
    name:        'Bytownite',
    trade_name:  false,
    mindat_id:   796,

    physical: {
      id:            796,
      longid:        'bytownite',
      guid:          'e5f6a7b8-c9d0-1234-efab-345678901234',
      name:          'Bytownite (plagioclase feldspar — An70–90)',
      ima_formula:   '(Ca,Na)(Al,Si)₄O₈',
      mindat_formula: '(Ca,Na)(Al,Si)4O8',
      ima_status:    'A',
      ima_year:      1835,
      strunzten:     '9.FA.35',
      dana8ed:       '76.1.3.5',
      crystal_system: 'Triclinic',
      hardness_min:  6.0,
      hardness_max:  6.5,
      specific_gravity_min: 2.72,
      specific_gravity_max: 2.75,
      cleavage:      'Perfect on {001}, good on {010}',
      fracture:      'Uneven to conchoidal',
      tenacity:      'Brittle',
      luster:        ['Vitreous'],
      diaphaneity:   ['Transparent', 'Translucent'],
      colour:        'Colourless, white, pale yellow, grey; gemmy specimens golden-yellow',
      streak:        'White',
      fluorescence:  null,
      ri_min:        1.563,
      ri_max:        1.578,
      birefringence: 0.013,
      optical_type:  'B',
      shortdesc:     'Calcium-rich plagioclase feldspar (An70–90). Gemmy golden crystals from Mexico used as collectors\' gems. Named for Bytown (now Ottawa), Canada.',
      updttime:      '2024-03-30T00:00:00Z',
      mindat_url:    'https://www.mindat.org/min-796.html',
      piezoelectric:     false,
      safe_for_water:    true,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Bytownite',
      refractive_index: { n_alpha: 1.563, n_beta: 1.568, n_gamma: 1.578 },
      birefringence:    0.013,
      optical_sign:     '+',
      dispersion:       'Weak',
      pleochroism:      null,
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 560, max: 600 },
      spectra:          [],
    },

    color: {
      primary_color:          'Golden yellow',
      color_variants:         ['Pale yellow', 'Colourless', 'White', 'Grey'],
      dominant_wavelength_nm: 580,
      oklch:                  { l: 0.82, c: 0.13, h: 82 },
      hex:                    '#f0d060',
      munsell:                '2.5Y 8/8',
      color_temperature_k:    4000,
      psychological_effects:  ['Solar radiance', 'Optimism', 'Clarity', 'Grounded confidence'],
      harmonics: {
        complementary_hue: 262,
        triadic_hues:      [202, 322],
        analogous_range:   [62, 102],
      },
    },

    color_layer: 'natural',
    yin_yang_pair: 'yang',

    metaphysical: {
      mineral_name:     'Bytownite',
      chakra_primary:   'Solar Plexus',
      chakra_secondary: ['Crown', 'Third Eye'],
      element:          ['Fire', 'Air'],
      planet:           ['Sun', 'Jupiter'],
      archetype:        ['The Golden One', 'The Sovereign'],
      zodiac:           ['Leo', 'Sagittarius'],
      numerology:       1,
      angel_number:     111,
      intention:        'I radiate solar confidence. My will is clear and my path is golden.',
      traditions:       ['Crystal healing', 'Vedic gem lore (similar to golden labradorite)'],
      properties:       [
        'Rare golden variety of labradorite-group plagioclase',
        'Stimulates personal power, optimism, and solar confidence',
        'Supports clear decision-making and aligned action',
        'Enhances creativity and the will to manifest',
        'Collector gem — faceted specimens from Mexico',
      ],
      gaia_resonance:   'SovereignCore + QuantumNexus',
      safety_warning:   'Calcium feldspar — generally safe for water cleansing. Avoid prolonged immersion as feldspar can develop surface hazing over time. Not recommended for extended water elixir preparation; short rinse is fine.',
    },
  },

];

export default BATCH_B9;
