"""
gaia/db/models.py
=================
GAIA-OS ORM model stubs.
Canon reference: C04 (Human/Gaian Twin Architecture),
                 C17 (Persistent Memory and Identity Architecture)

These are typed dataclass stubs that mirror the SQLAlchemy / Alembic
schema defined in the full DB layer. They are used by:
  - tests that import from gaia.db or gaia.db.models
  - API layer serialization helpers
  - Any module that needs typed memory / audit / session objects
    without pulling in the full SQLAlchemy dependency chain.

The real SQLAlchemy models live in gaia/db/orm/ (generated by Alembic).
When those models are fully wired, these stubs will be replaced by
direct re-exports from gaia.db.orm.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# MemoryRecord
# ---------------------------------------------------------------------------

@dataclass
class MemoryRecord:
    """
    A single persisted memory entry.

    Mirrors the `memory_records` table schema.

    Fields:
        id:           UUID primary key (auto-generated).
        gaian_id:     The Gaian Twin this memory belongs to.
        content:      The memory content (text or JSON string).
        memory_type:  e.g. "episodic", "semantic", "shadow", "identity".
        session_id:   Session in which this memory was created.
        phi:          Coherence / integration score at time of creation.
        tags:         Searchable tag list.
        created_at:   Unix timestamp.
        metadata:     Arbitrary dict for extended fields.
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    gaian_id: str = ""
    content: str = ""
    memory_type: str = "episodic"
    session_id: str = ""
    phi: float = 0.0
    tags: List[str] = field(default_factory=list)
    created_at: float = field(default_factory=time.time)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "gaian_id": self.gaian_id,
            "content": self.content,
            "memory_type": self.memory_type,
            "session_id": self.session_id,
            "phi": self.phi,
            "tags": self.tags,
            "created_at": self.created_at,
            "metadata": self.metadata,
        }


# ---------------------------------------------------------------------------
# AuditLog
# ---------------------------------------------------------------------------

@dataclass
class AuditLog:
    """
    A single audit log entry.

    Mirrors the `audit_logs` table schema.
    Used by permission system, safety controller, and Sentinel.

    Fields:
        id:         UUID primary key.
        actor:      Who performed the action (gaian_id, agent_id, or system).
        action:     What was done (e.g. "WRITE_MEMORY", "ISSUE_HALT").
        resource:   What was acted upon.
        outcome:    "granted" or "denied".
        reason:     Human-readable reason string.
        timestamp:  Unix timestamp.
        context:    Arbitrary dict for extended diagnostic fields.
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    actor: str = ""
    action: str = ""
    resource: str = ""
    outcome: str = "granted"
    reason: str = ""
    timestamp: float = field(default_factory=time.time)
    context: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "actor": self.actor,
            "action": self.action,
            "resource": self.resource,
            "outcome": self.outcome,
            "reason": self.reason,
            "timestamp": self.timestamp,
            "context": self.context,
        }


# ---------------------------------------------------------------------------
# SessionRecord
# ---------------------------------------------------------------------------

@dataclass
class SessionRecord:
    """
    A persisted GAIA session.

    Mirrors the `sessions` table schema.

    Fields:
        id:           Session UUID.
        gaian_id:     Owning Gaian Twin.
        started_at:   Unix timestamp of session start.
        ended_at:     Unix timestamp of session end (None if active).
        mode_history: List of (timestamp, mode) tuples.
        phi_peak:     Highest phi recorded during this session.
        metadata:     Arbitrary dict.
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    gaian_id: str = ""
    started_at: float = field(default_factory=time.time)
    ended_at: Optional[float] = None
    mode_history: List[Dict[str, Any]] = field(default_factory=list)
    phi_peak: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def is_active(self) -> bool:
        return self.ended_at is None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "gaian_id": self.gaian_id,
            "started_at": self.started_at,
            "ended_at": self.ended_at,
            "is_active": self.is_active,
            "mode_history": self.mode_history,
            "phi_peak": self.phi_peak,
            "metadata": self.metadata,
        }


# ---------------------------------------------------------------------------
# CanonRef
# ---------------------------------------------------------------------------

@dataclass
class CanonRef:
    """
    A reference to a canon document.
    Used in memory records, audit logs, and session metadata.

    Fields:
        canon_id:   e.g. "C167", "BWL-016", "PRIMORDIAL".
        title:      Human-readable title.
        tier:       CanonTier string value.
        path:       Relative path to the canon document.
    """
    canon_id: str
    title: str = ""
    tier: str = "NUMBERED"
    path: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "canon_id": self.canon_id,
            "title": self.title,
            "tier": self.tier,
            "path": self.path,
        }
